import { TCategorySummary } from "@/types";

export const CATEGORY_SUMMARY_STUB: TCategorySummary[] = [
  {
    id: "Executive",
    count: 74,
    title: "Executive",
    singularAndPlural: ["policy", "policies"],
    families: [
      {
        family_slug: "clean-power-2030-action-plan_c2c5",
        family_name: "Clean Power 2030 Action Plan",
        family_description:
          "The Clean Power 2030 Action Plan sets out how the UK government will work with the clean power sector, including industry, trade unions, investors, policy makers and others, to achieve its clean power goal. The goal is to have clean sources produce at least as much power as consumed in the whole year, and at least 95% of the power generated. Unabated gas supply will be used only when essential. 43-50 GW of offshore wind, 27-29 GW of onshore wind, and 45-47 GW of solar power will be added.The UK will invest around £40 billion per year for six years from 2025 to 2030. Actions to accelerate the delivery of clean power include: reforming grid connections; reforming the planning system; renewal and nuclear project delivery; electricity market reform; short-duration energy storage and flexibility; long-duration flexible capacity; more sustainable supply chains and a skilled workforce.The plan will reduce over-reliance on fossil fuels and exposure to the cost of globally traded oil and gas in the context of recent global insecurity.",
        family_category: "Executive",
        family_date: "2024-12-13T00:00:00+00:00",
        family_source: "CCLW",
        corpus_import_id: "CCLW.corpus.i00000001.n0000",
        corpus_type_name: "Laws and Policies",
        family_geographies: ["GBR"],
        family_metadata: {},
        family_title_match: false,
        family_description_match: false,
        total_passage_hits: 0,
        family_documents: [],
        continuation_token: null,
        prev_continuation_token: null,
      },
      {
        family_slug: "english-devolution-white-paper_463a",
        family_name: "English Devolution White Paper",
        family_description:
          "<p>In the area of environment and climate change, the UK government has committed to making Britain a clean energy superpower. So that Strategic Authorities can play their role in this mission, it will make the following changes: </p>\n<ul>\n<li>Mayors will be handed control of retrofit funding as part of the Integrated Settlements, providing a strengthened route to local delivery of the Warm Homes Plan.</li>\n<li>Strategic Authorities will have a strategic role in the delivery of the Great British Energy Local Power Plans, delivering local sustainable energy generation.</li>\n<li>They will also have a role in the wider energy system, delivering the transition to Net Zero and to a low-cost, clean power energy system by 2030, become the zoning co-ordinators for local heat networks, and with their plans taken into account in the National Energy System operators’ Regional Energy Strategic Plans.</li>\n<li>Finally, we will expand Strategic Authorities’ role in leading Local Nature Recovery Strategies.</li>\n</ul>\n<p>In addition, future opportunities for devolution and partnership working will be explored with Strategic Authorities. These could include issues like water management, the circular economy, pollution, or flood resilience. The UK government will also explore how Strategic Authorities and Mayors can provide greater local leadership in responding to the impacts of climate change, and a better route for rural communities to be considered in local policy decision making.   </p>",
        family_category: "Executive",
        family_date: "2024-12-16T00:00:00+00:00",
        family_source: "CCLW",
        corpus_import_id: "CCLW.corpus.i00000001.n0000",
        corpus_type_name: "Laws and Policies",
        family_geographies: ["GBR"],
        family_metadata: {},
        family_title_match: false,
        family_description_match: false,
        total_passage_hits: 0,
        family_documents: [],
        continuation_token: null,
        prev_continuation_token: null,
      },
      {
        family_slug: "warm-homes-plan_dbdf",
        family_name: "Warm Homes Plan",
        family_description:
          "<p>This Plan will help people save money on energy bills and deliver warmer, cleaner energy to heat homes, with up to 300,000 homes to benefit from upgrades next year, such as new insulation and solar and heat pumps. Working alongside the UK government’s mission to make Britain a clean energy superpower, the Warm Homes Plan will ensure millions more households benefit from homegrown energy delivered by every new turbine, solar panel or pylon built on the path to energy independence. The UK government works closely with local government to execute this Plan.</p>",
        family_category: "Executive",
        family_date: "2024-11-21T00:00:00+00:00",
        family_source: "CCLW",
        corpus_import_id: "CCLW.corpus.i00000001.n0000",
        corpus_type_name: "Laws and Policies",
        family_geographies: ["GBR"],
        family_metadata: {},
        family_title_match: false,
        family_description_match: false,
        total_passage_hits: 0,
        family_documents: [],
        continuation_token: null,
        prev_continuation_token: null,
      },
      {
        family_slug: "adapting-the-uks-transport-system-to-the-impacts-of-climate-change_7ec1",
        family_name: "Transport Adaptation Strategy",
        family_description:
          "This transport adaptation strategy includes actions and policies to enhance climate adaptation planning across the transport sector, ensure these plans are achieved, and lead to improved climate resilience in the transport system. This strategy will support transport infrastructure operators in recognising the opportunities, including cost savings, that come with adaptation.\nAs the climate changes, travel disruption from extreme weather could have an increasing impact on day-to-day lives if action is not taken to manage the risk. The Government's 2023 National Risk Register identified risks such as extreme heat, storms and flooding had become more likely due to climate change, with the trend expected to continue over the coming decades.",
        family_category: "Executive",
        family_date: "2024-04-03T00:00:00+00:00",
        family_source: "CPR",
        corpus_import_id: "CPR.corpus.i00000592.n0000",
        corpus_type_name: "Laws and Policies",
        family_geographies: ["GBR"],
        family_metadata: {},
        family_title_match: false,
        family_description_match: false,
        total_passage_hits: 0,
        family_documents: [],
        continuation_token: null,
        prev_continuation_token: null,
      },
      {
        family_slug: "delivering-30by30-on-land-in-england_9dee",
        family_name: "Delivering 30by30 on land in England",
        family_description:
          "<p>The United Kingdom has committed to protecting 30% of the UK's land by 2030 (also know as '30by30'). The Delivering 30by30 on land in England strategy sets out how the UK government is taking action to achieve its 30 by 30 target and protect nature and biodiversity in the UK. It also introduces the 30by30 criteria, which outlines how different areas can also contribute to achieving land protection targets. The strategy builds on the proposals made in the Environmental Improvement Plan 2023, which recommends achieving the 30 by 30 target through \"ensuring effective policy and statutory safeguards and powers in place to improve management for nature, prevent degradation and ensure appropriate access for people... designature new protected areas and restore or create wildlife rich habitate outside of these... and invest in habitata restoration across our protected areas and beyond\".&nbsp;</p>\n",
        family_category: "Executive",
        family_date: "2023-12-09T00:00:00+00:00",
        family_source: "CCLW",
        corpus_import_id: "CCLW.corpus.i00000001.n0000",
        corpus_type_name: "Laws and Policies",
        family_geographies: ["GBR"],
        family_metadata: {},
        family_title_match: false,
        family_description_match: false,
        total_passage_hits: 0,
        family_documents: [],
        continuation_token: null,
        prev_continuation_token: null,
      },
    ],
  },
  {
    id: "Legislative",
    title: "Legislative",
    count: 33,
    singularAndPlural: ["law", "laws"],
    families: [
      {
        family_slug: "the-climate-change-targeted-greenhouse-gases-order-2023_d2ab",
        family_name: "The Climate Change (Targeted Greenhouse Gases) Order 2023",
        family_description:
          "<p>This Order extends the scope of emissions captured and reported under the Climate Change Act 2008  by including nitrogen trifluoride (“NF3”) as a targeted greenhouse gas from the coming into force of the Order.</p>\n<p></p>\n",
        family_category: "Legislative",
        family_date: "2023-02-02T00:00:00+00:00",
        family_source: "CCLW",
        corpus_import_id: "CCLW.corpus.i00000001.n0000",
        corpus_type_name: "Laws and Policies",
        family_geographies: ["GBR"],
        family_metadata: {},
        family_title_match: false,
        family_description_match: false,
        total_passage_hits: 0,
        family_documents: [],
        continuation_token: null,
        prev_continuation_token: null,
      },
      {
        family_slug: "vehicle-emissions-trading-schemes-order-2023_4e6d",
        family_name: "The Vehicle Emissions Trading Schemes Order 2023",
        family_description:
          "<p>This Order was made in terms of the Climate Change Act 2008. It establishes a zero-emission vehicle (ZEV) mandate and CO2 emissions standards for cars and vans in Great Britain. It requires manufacturers to ensure that 80% of new vehicles and 70% of new vans sold are zero-emission by 2030, increasing to 100% by 2035. It also sets a fine for qualifying manufacturers failing to meet the targets and allows them to purchase credits from manufacturers with a surplus.&nbsp;&nbsp;</p>\n<p></p>\n",
        family_category: "Legislative",
        family_date: "2024-01-03T00:00:00+00:00",
        family_source: "CCLW",
        corpus_import_id: "CCLW.corpus.i00000001.n0000",
        corpus_type_name: "Laws and Policies",
        family_geographies: ["GBR"],
        family_metadata: {},
        family_title_match: false,
        family_description_match: false,
        total_passage_hits: 0,
        family_documents: [],
        continuation_token: null,
        prev_continuation_token: null,
      },
      {
        family_slug: "energy-act-2023_c2f5",
        family_name: "Energy Act 2023",
        family_description:
          "<p>The Act provides for energy production and security and regulates the energy market in the UK. To that end, it makes provisions ranging from commercial carbon capture and storage arrangements, low-carbon heat schemes and hydrogen grid trials, and energy smart appliances, among others. Also, it provides a legislative basis for the establishment of a publicly owned company called the National Energy System Operator (NESO), which expands on the role of the current National Grid Electricity System Operator to cover gas and to accommodate a more decentralised, variable electricity system based mainly on renewables.</p>",
        family_category: "Legislative",
        family_date: "2023-10-26T00:00:00+00:00",
        family_source: "CCLW",
        corpus_import_id: "CCLW.corpus.i00000001.n0000",
        corpus_type_name: "Laws and Policies",
        family_geographies: ["GBR"],
        family_metadata: {},
        family_title_match: false,
        family_description_match: false,
        total_passage_hits: 0,
        family_documents: [],
        continuation_token: null,
        prev_continuation_token: null,
      },
      {
        family_slug: "anti-greenwashing-rule_705f",
        family_name: "Anti-greenwashing rule ",
        family_description:
          "<p>The Financial Conduct Authority (FCA) Handbook includes an 'anti-greenwashing rule' (ESG 4.3.1R), which applies to all communications that mention sustainability-linked characteristics of products or services available for clients in the UK by FCA-authorised firms. The rule tooke ffect from 31 May 2024.&nbsp;</p>\n",
        family_category: "Legislative",
        family_date: "2024-05-31T00:00:00+00:00",
        family_source: "CCLW",
        corpus_import_id: "CCLW.corpus.i00000001.n0000",
        corpus_type_name: "Laws and Policies",
        family_geographies: ["GBR"],
        family_metadata: {},
        family_title_match: false,
        family_description_match: false,
        total_passage_hits: 0,
        family_documents: [],
        continuation_token: null,
        prev_continuation_token: null,
      },
      {
        family_slug: "water-act-2014-creation-of-flood-re-scheme_2c5a",
        family_name: "Water Act 2014 (creation of Flood Re scheme)",
        family_description:
          "Flood Re is a hybrid public private reinsurance scheme introduced by the UK Government under Part 4 of the Water Act 2014. It was designed in partnership with insurers aimed at making the flood cover part of household insurance policies more affordable. Every insurer that offers home insurance in the UK is required to pay into the Flood Re Scheme. Funds from this levy are then used to cover the flood risks in home insurance policies.",
        family_category: "Legislative",
        family_date: "2016-04-04T00:00:00+00:00",
        family_source: "CCLW",
        corpus_import_id: "CCLW.corpus.i00000001.n0000",
        corpus_type_name: "Laws and Policies",
        family_geographies: ["GBR"],
        family_metadata: {},
        family_title_match: false,
        family_description_match: false,
        total_passage_hits: 0,
        family_documents: [],
        continuation_token: null,
        prev_continuation_token: null,
      },
    ],
  },
  {
    id: "UNFCCC",
    title: "UNFCCC",
    count: 19,
    singularAndPlural: ["document", "documents"],
    families: [
      {
        family_slug: "united-kingdom-national-inventory-report-nir-2025_3a70",
        family_name: "United Kingdom National Inventory Report (NIR). 2025",
        family_description: "<p>United Kingdom National Inventory Report (NIR). 2025</p>",
        family_category: "UNFCCC",
        family_date: "2025-04-15T00:00:00+00:00",
        family_source: "UNFCCC",
        corpus_import_id: "UNFCCC.corpus.i00000001.n0000",
        corpus_type_name: "Intl. agreements",
        family_geographies: ["GBR"],
        family_metadata: {},
        family_title_match: false,
        family_description_match: false,
        total_passage_hits: 0,
        family_documents: [],
        continuation_token: null,
        prev_continuation_token: null,
      },
      {
        family_slug: "the-uk-s-2035-ndc-ictu_f5f0",
        family_name: "United Kingdom  Nationally Determined Contribution. NDC3.0",
        family_description: "<p>The UK's 2035 NDC ICTU</p>",
        family_category: "UNFCCC",
        family_date: "2025-01-30T00:00:00+00:00",
        family_source: "UNFCCC",
        corpus_import_id: "UNFCCC.corpus.i00000001.n0000",
        corpus_type_name: "Intl. agreements",
        family_geographies: ["GBR"],
        family_metadata: {},
        family_title_match: false,
        family_description_match: false,
        total_passage_hits: 0,
        family_documents: [],
        continuation_token: null,
        prev_continuation_token: null,
      },
      {
        family_slug: "united-kingdom-national-inventory-report-nir-2024_1deb",
        family_name: "United Kingdom National Inventory Report (NIR). 2024",
        family_description: "<p>United Kingdom National Inventory Report (NIR). 2024</p>",
        family_category: "UNFCCC",
        family_date: "2024-12-24T00:00:00+00:00",
        family_source: "UNFCCC",
        corpus_import_id: "UNFCCC.corpus.i00000001.n0000",
        corpus_type_name: "Intl. agreements",
        family_geographies: ["GBR"],
        family_metadata: {},
        family_title_match: false,
        family_description_match: false,
        total_passage_hits: 0,
        family_documents: [],
        continuation_token: null,
        prev_continuation_token: null,
      },
      {
        family_slug: "united-kingdom-biennial-transparency-report-btr1_2c7d",
        family_name: "United Kingdom Biennial Transparency Report. BTR1",
        family_description: "<p>United Kingdom Biennial Transparency Report. BTR1</p>",
        family_category: "UNFCCC",
        family_date: "2024-12-24T00:00:00+00:00",
        family_source: "UNFCCC",
        corpus_import_id: "UNFCCC.corpus.i00000001.n0000",
        corpus_type_name: "Intl. agreements",
        family_geographies: ["GBR"],
        family_metadata: {},
        family_title_match: false,
        family_description_match: false,
        total_passage_hits: 0,
        family_documents: [],
        continuation_token: null,
        prev_continuation_token: null,
      },
      {
        family_slug: "united-kingdom-national-adaptation-plan-nap1_c7e1",
        family_name: "United Kingdom National Adaptation Plan. NAP3",
        family_description: "<p>United Kingdom National Adaptation Plan. NAP3</p>",
        family_category: "UNFCCC",
        family_date: "2023-07-18T00:00:00+00:00",
        family_source: "UNFCCC",
        corpus_import_id: "UNFCCC.corpus.i00000001.n0000",
        corpus_type_name: "Intl. agreements",
        family_geographies: ["GBR"],
        family_metadata: {},
        family_title_match: false,
        family_description_match: false,
        total_passage_hits: 0,
        family_documents: [],
        continuation_token: null,
        prev_continuation_token: null,
      },
    ],
  },
  {
    id: "Reports",
    title: "Reports",
    count: 73,
    singularAndPlural: ["report", "reports"],
    families: [
      {
        family_slug: "aviva-plc-corporate-transition-plan-2021-2024_2e00",
        family_name: "Aviva plc Corporate Transition Plan 2021 - 2024",
        family_description: "<p>Aviva plc Corporate Transition Plan 2021 - 2024</p>",
        family_category: "Reports",
        family_date: "2025-05-12T00:00:00+00:00",
        family_source: "CPR",
        corpus_import_id: "CPR.corpus.i00000002.n0000",
        corpus_type_name: "Reports",
        family_geographies: ["GBR"],
        family_metadata: {},
        family_title_match: false,
        family_description_match: false,
        total_passage_hits: 0,
        family_documents: [],
        continuation_token: null,
        prev_continuation_token: null,
      },
      {
        family_slug: "aviva-plc-sustainability-report-2024_d3cf",
        family_name: "Aviva plc Sustainability Report 2024",
        family_description: "<p>Aviva plc Sustainability Report 2024</p>",
        family_category: "Reports",
        family_date: "2025-05-12T00:00:00+00:00",
        family_source: "CPR",
        corpus_import_id: "CPR.corpus.i00000002.n0000",
        corpus_type_name: "Reports",
        family_geographies: ["GBR", "GB-ENG"],
        family_metadata: {},
        family_title_match: false,
        family_description_match: false,
        total_passage_hits: 0,
        family_documents: [],
        continuation_token: null,
        prev_continuation_token: null,
      },
      {
        family_slug: "aviva-plc-annual-mandatory-report-2024_4dcb",
        family_name: "Aviva plc Annual Mandatory Report 2024",
        family_description: "<p>Aviva plc Annual Mandatory Report 2024</p>",
        family_category: "Reports",
        family_date: "2025-05-12T00:00:00+00:00",
        family_source: "CPR",
        corpus_import_id: "CPR.corpus.i00000002.n0000",
        corpus_type_name: "Reports",
        family_geographies: ["GBR", "GB-SCT"],
        family_metadata: {},
        family_title_match: false,
        family_description_match: false,
        total_passage_hits: 0,
        family_documents: [],
        continuation_token: null,
        prev_continuation_token: null,
      },
      {
        family_slug: "wizz-air-holdings-plc-co2-emission-report-2025_b820",
        family_name: "Wizz Air Holdings Plc CO2 Emission report 2025",
        family_description: "<p>Wizz Air Holdings Plc CO2 Emission report 2025</p>",
        family_category: "Reports",
        family_date: "2025-05-05T00:00:00+00:00",
        family_source: "CPR",
        corpus_import_id: "CPR.corpus.i00000002.n0000",
        corpus_type_name: "Reports",
        family_geographies: ["GBR", "GB-WLS"],
        family_metadata: {},
        family_title_match: false,
        family_description_match: false,
        total_passage_hits: 0,
        family_documents: [],
        continuation_token: null,
        prev_continuation_token: null,
      },
      {
        family_slug: "xpeng-inc-annual-mandatory-report-2024_0e04",
        family_name: "XPeng Inc. Annual Mandatory Report 2024",
        family_description: "<p>XPeng Inc. Annual Mandatory Report 2024</p>",
        family_category: "Reports",
        family_date: "2025-04-16T00:00:00+00:00",
        family_source: "CPR",
        corpus_import_id: "CPR.corpus.i00000002.n0000",
        corpus_type_name: "Reports",
        family_geographies: ["GBR"],
        family_metadata: {},
        family_title_match: false,
        family_description_match: false,
        total_passage_hits: 0,
        family_documents: [],
        continuation_token: null,
        prev_continuation_token: null,
      },
    ],
  },
  {
    id: "MCF",
    title: "MCF",
    count: 0,
    singularAndPlural: ["document", "documents"],
    families: [],
  },
  {
    id: "Litigation",
    title: "Litigation",
    count: 0,
    singularAndPlural: ["case", "cases"],
    families: [],
  },
];
