import { TFamilyNew } from "@/types";

export const FAMILY_NEW_STUB: TFamilyNew = {
  import_id: "Sabin.family.14461.0",
  title: "Environment Victoria vs the EPA et. al.",
  concepts: [
    {
      id: "Supreme Court of Victoria",
      ids: [],
      type: "legal_entity",
      relation: "jurisdiction",
      preferred_label: "Supreme Court of Victoria",
      subconcept_of_labels: ["Victoria"],
    },
    {
      id: "Australia",
      ids: [],
      type: "legal_entity",
      relation: "jurisdiction",
      preferred_label: "Australia",
      subconcept_of_labels: [],
    },
    {
      id: "Victoria",
      ids: [],
      type: "legal_entity",
      relation: "jurisdiction",
      preferred_label: "Victoria",
      subconcept_of_labels: ["Australia"],
    },
    {
      id: "Australia",
      ids: [],
      type: "law",
      relation: "principal_law",
      preferred_label: "Australia",
      subconcept_of_labels: [],
    },
    {
      id: "Climate Change Act 2017 (Victoria)",
      ids: [],
      type: "law",
      relation: "principal_law",
      preferred_label: "Climate Change Act 2017 (Victoria)",
      subconcept_of_labels: ["Australia"],
    },
    {
      id: "Environmental Protection Act 1970 (Victoria)",
      ids: [],
      type: "law",
      relation: "principal_law",
      preferred_label: "Environmental Protection Act 1970 (Victoria)",
      subconcept_of_labels: ["Australia"],
    },
    {
      id: "Suits against governments",
      ids: [],
      type: "legal_category",
      relation: "category",
      preferred_label: "Suits against governments",
      subconcept_of_labels: [],
    },
    {
      id: "Environmental permitting",
      ids: [],
      type: "legal_category",
      relation: "category",
      preferred_label: "Environmental permitting",
      subconcept_of_labels: ["Trade and Investment"],
    },
    {
      id: "Trade and Investment",
      ids: [],
      type: "legal_category",
      relation: "category",
      preferred_label: "Trade and Investment",
      subconcept_of_labels: ["Suits against governments"],
    },
  ],
  corpus: {
    organisation_id: 11,
    import_id: "Academic.corpus.Litigation.n0000",
    title: "Litigation",
    corpus_type_name: "Litigation",
  },
  corpus_id: "Academic.corpus.Litigation.n0000",
  organisation: "Sabin",
  summary:
    "On September 20, 2021, Environment Victoria launched a legal action against the Environment Protection Authority (EPA) and AGL Energy, EnergyAustralia, and Alinta, owners of Victoria’s three remaining coal-burning power stations. The plaintiffs question EPA’s review of three power station licenses, which lacked more stringent limits on GHG emissions. Environment Victoria argues that the EPA has failed to require best practice management of toxic emissions, take proper account of the environmental principles in the Environment Protection Act and consider key sections of the 2017 Climate Change Act. Environment Australia asks the court to revoke, amend, and attach certain conditions to the licenses. \r\n\r\nIn November 2017, the EPA announced the review of Victoria’s coal power stations. In March 2021, the EPA announced new license conditions for the state’s three remaining coal power stations. In August 2021, the EPA granted the permits and capped GHG emissions at “approximately current levels,” instead of lowering the required standards. Victoria’s Climate Change Act requires the EPA to consider climate change in their review of coal power station licenses, which, according to the plaintiffs, the EPA failed to do. The emissions form the coal-burning power stations represent about 40% of Victoria’s total emissions. The plaintiffs also question the limits on toxic air pollution, including sulfur dioxide, fine particles (PM2.5) and mercury. \r\n\r\nThe trial commenced before Justice James Gorton of the Victorian Supreme Court on October 18, 2022. The Supreme Court upheld EPA's limits on emissions and pollutants from coal powered plants.\r\n",
  geographies: ["AUS", "AU-VIC"],
  published_date: "2021-01-01T00:00:00Z",
  last_updated_date: "2021-09-16T00:00:00Z",
  slug: "environment-victoria-vs-the-epa-et-al_2c73",
  category: "Litigation",
  corpus_type_name: "Litigation",
  collections: [],
  events: [
    {
      title: "Filing Year For Action",
      date: "2021-01-01T00:00:00Z",
      event_type: "Filing Year For Action",
      status: "OK",
      metadata: {
        event_type: ["Filing Year For Action"],
        description: ["Filing Year For Action"],
        datetime_event_name: ["Filing Year For Action"],
      },
    },
    {
      title: "petition",
      date: "2021-09-16T00:00:00Z",
      event_type: "Petition",
      status: "OK",
      metadata: {
        event_type: ["Petition"],
        description: ["Originating Motion"],
        datetime_event_name: ["Filing Year For Action"],
      },
    },
  ],
  documents: [
    {
      import_id: "Sabin.document.14461.14462",
      slug: "environment-victoria-vs-the-epa-et-al-petition_4093",
      title: "Environment Victoria vs the EPA et. al. - petition",
      cdn_object: "https://cdn.climatepolicyradar.org/AUS/2021/environment-victoria-vs-the-epa-et-al_cc4e19ff5e29071cb4f181f5353001a7.pdf",
      variant: "Original Language",
      md5_sum: "cc4e19ff5e29071cb4f181f5353001a7",
      source_url: "https://climatecasechart.com/wp-content/uploads/non-us-case-documents/2021/20210916_S-ECI-2021-03415_petition.pdf",
      content_type: "application/pdf",
      language: "eng",
      languages: ["eng"],
      document_type: null,
      document_role: null,
      events: [
        {
          title: "petition",
          date: "2021-09-16T00:00:00Z",
          event_type: "Petition",
          status: "OK",
          metadata: {
            event_type: ["Petition"],
            description: ["Originating Motion"],
            datetime_event_name: ["Filing Year For Action"],
          },
        },
      ],
    },
  ],
  metadata: {
    id: ["14461"],
    status: ["Decided"],
    case_number: ["S ECI 2021 03415"],
    core_object: [
      "Whether the EPA complied with the Climate Change Act when issuing a new license for coal-burning power stations that failed to lower the limits of GHG emissions.",
    ],
    original_case_name: [],
    concept_preferred_label: [
      "jurisdiction/Supreme Court of Victoria",
      "jurisdiction/Australia",
      "jurisdiction/Victoria",
      "principal_law/Australia",
      "principal_law/Climate Change Act 2017 (Victoria)",
      "principal_law/Environmental Protection Act 1970 (Victoria)",
      "category/Suits against governments",
      "category/Environmental permitting",
      "category/Trade and Investment",
    ],
  },
};
