import { TTarget } from "@/types";

export const TARGETS_STUB: TTarget[] = [
  {
    ID: "1096",
    "Target type": "base_year_target",
    Source: "law",
    Description: "Reduce between 36.1% and 38.9% of its projected emissions by 2020 against a 2010 baseline",
    "GHG target": "TRUE",
    Year: "2020",
    "Base year period": "2010",
    "Single year": "FALSE",
    Geography: "Brazil",
    "Geography ISO": "BRA",
    Sector: "Economy-wide",
    "CCLW legislation ID": "1092",
    Scopes: "Economy Wide",
    "Visibility status": "published",
    "CPR family ID": "CCLW.family.1092.0",
    "Net zero target?": "FALSE",
    Comment: "",
    "family-slug": "law-12-187-2009-establishing-the-national-policy-on-climate-change-npcc-regulated-by-decree-7-390-2010_dd44",
    "family-name": "Law 12.187/2009, establishing the National Policy on Climate Change (NPCC), regulated by Decree 7.390/2010",
  },
  {
    ID: "1094",
    "Target type": "base_year_target",
    Source: "law",
    Description:
      "Implementation of the National Policy for Energy Efficiency that will result in a gradual energy saving up to 106 TWh/year to be reached in 2030, avoiding emissions of around 30 million tons of CO2 in that year by 2030 against a 2007 baseline",
    "GHG target": "TRUE",
    Year: "2030",
    "Base year period": "2007",
    "Single year": "FALSE",
    Geography: "Brazil",
    "Geography ISO": "BRA",
    Sector: "Energy",
    "CCLW legislation ID": "1094",
    Scopes: "Energy Efficiency",
    "Visibility status": "published",
    "CPR family ID": "CCLW.family.1094.0",
    "Net zero target?": "FALSE",
    Comment: "",
    "family-slug": "national-plan-on-climate-change_10eb",
    "family-name": "National Plan on Climate Change",
  },
  {
    ID: "1093",
    "Target type": "base_year_target",
    Source: "law",
    Description:
      "Replacement of one million old fridges per year, for ten years, with the collection of three million tCO2eq/year of CFCs (gases that also deplete the ozone layer) by 2017 against a 2007 baseline",
    "GHG target": "TRUE",
    Year: "2017",
    "Base year period": "2007",
    "Single year": "FALSE",
    Geography: "Brazil",
    "Geography ISO": "BRA",
    Sector: "Buildings",
    "CCLW legislation ID": "1094",
    Scopes: "Energy Efficiency",
    "Visibility status": "published",
    "CPR family ID": "CCLW.family.1094.0",
    "Net zero target?": "FALSE",
    Comment: "",
    "family-slug": "national-plan-on-climate-change_10eb",
    "family-name": "National Plan on Climate Change",
  },
  {
    ID: "1088",
    "Target type": "trajectory_target",
    Source: "law",
    Description:
      "Reduction of 40% in the average deforestation rate by 2006-2009 period in relation to the average rate of the ten years reference period used in the Amazon Fund (1996-2005). For each of the next two periods of four years, reach 30% of extra reduction, in relation to the previous period.     In the case of the Amazon bioma, achieving this specific objective can avoid emissions of around 4.8 billion tons of carbon dioxide between 2006 and 2017, considering a biomass carbon stock of 100 tC/ha. This value will be reevaluated after the completion of the carbon stocks inventory, to be supported by the National Forest Inventory.  by 2006-2009 compared with a 1996-2005 scenario",
    "GHG target": "TRUE",
    Year: "2009",
    "Base year period": "1996-2005",
    "Single year": "FALSE",
    Geography: "Brazil",
    "Geography ISO": "BRA",
    Sector: "LULUCF",
    "CCLW legislation ID": "1094",
    Scopes: "Preservation",
    "Visibility status": "published",
    "CPR family ID": "CCLW.family.1094.0",
    "Net zero target?": "FALSE",
    Comment: "",
    "family-slug": "national-plan-on-climate-change_10eb",
    "family-name": "National Plan on Climate Change",
  },
  {
    ID: "1082",
    "Target type": "trajectory_target",
    Source: "law",
    Description:
      "Ethanol - encourages industry to achieve an average annual consumption increase of 11% by 2017. Produced from crops raised in areas de ned in the Sugarcane Zoning Program, currently being implemented, it should prevent the emission of 508 million tCO2 during the period.",
    "GHG target": "TRUE",
    Year: "2017",
    "Base year period": "2007",
    "Single year": "FALSE",
    Geography: "Brazil",
    "Geography ISO": "BRA",
    Sector: "Energy",
    "CCLW legislation ID": "1094",
    Scopes: "Renewable Energy: Biofuels",
    "Visibility status": "published",
    "CPR family ID": "CCLW.family.1094.0",
    "Net zero target?": "FALSE",
    Comment: "",
    "family-slug": "national-plan-on-climate-change_10eb",
    "family-name": "National Plan on Climate Change",
  },
];
