version: "3.8"

services:
  navigator-frontend-cpr:
    labels:
      # Main front door for the environment
      shipyard.route: /
      shipyard.primary-route: true
      shipyard.host.cpr: '{"prefix": "cpr"}'
    build:
      context: .
      dockerfile: Dockerfile
      args:
        THEME: cpr
        # trunk-ignore(checkov/CKV_SECRET_6)
        ADOBE_API_KEY: f27f373000c74f22a7f3976caba43efe
        BACKEND_API_URL: https://cpr.staging.climatepolicyradar.org/api/v1
        # trunk-ignore(checkov/CKV_SECRET_9)
        BACKEND_API_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhbGxvd2VkX2NvcnBvcmFfaWRzIjpbIkFjYWRlbWljLmNvcnB1cy5MaXRpZ2F0aW9uLm4wMDAwIiwiQ0NMVy5jb3JwdXMuaTAwMDAwMDAxLm4wMDAwIiwiQ1BSLmNvcnB1cy5Hb2xkc3RhbmRhcmQubjAwMDAiLCJDUFIuY29ycHVzLmkwMDAwMDAwMS5uMDAwMCIsIkNQUi5jb3JwdXMuaTAwMDAwMDAyLm4wMDAwIiwiQ1BSLmNvcnB1cy5pMDAwMDA1ODkubjAwMDAiLCJDUFIuY29ycHVzLmkwMDAwMDU5MS5uMDAwMCIsIkNQUi5jb3JwdXMuaTAwMDAwNTkyLm4wMDAwIiwiTUNGLmNvcnB1cy5BRi5HdWlkYW5jZSIsIk1DRi5jb3JwdXMuQUYubjAwMDAiLCJNQ0YuY29ycHVzLkNJRi5HdWlkYW5jZSIsIk1DRi5jb3JwdXMuQ0lGLm4wMDAwIiwiTUNGLmNvcnB1cy5HQ0YuR3VpZGFuY2UiLCJNQ0YuY29ycHVzLkdDRi5uMDAwMCIsIk1DRi5jb3JwdXMuR0VGLkd1aWRhbmNlIiwiTUNGLmNvcnB1cy5HRUYubjAwMDAiLCJPRVAuY29ycHVzLmkwMDAwMDAwMS5uMDAwMCIsIlVOLmNvcnB1cy5VTkNCRC5uMDAwMCIsIlVOLmNvcnB1cy5VTkNDRC5uMDAwMCIsIlVORkNDQy5jb3JwdXMuaTAwMDAwMDAxLm4wMDAwIl0sInN1YiI6IkNQUiIsImF1ZCI6ImNwci5zdGFnaW5nLmNsaW1hdGVwb2xpY3lyYWRhci5vcmciLCJpc3MiOiJDbGltYXRlIFBvbGljeSBSYWRhciIsImV4cCI6MjA3NTQ2NjYxMC4wLCJpYXQiOjE3NTk5MzM4MTB9.EMOcQ6yPARwT5gdjbmj7qwiTYC497hyS__cQ_O6sbTQ
        CONCEPTS_API_URL: https://api.staging.climatepolicyradar.org
        TARGETS_URL: https://cpr-staging-targets-json-store.s3.eu-west-1.amazonaws.com
        APP_URL: https://cpr.staging.climatepolicyradar.org
    # Container listens on 8080
    ports:
      - "8080"

  navigator-frontend-cclw:
    labels:
      shipyard.route: /
      shipyard.host.cclw: '{"prefix": "cclw"}'
    build:
      context: .
      dockerfile: Dockerfile
      args:
        THEME: cclw
        # trunk-ignore(checkov/CKV_SECRET_6)
        ADOBE_API_KEY: f27f373000c74f22a7f3976caba43efe
        BACKEND_API_URL: https://cpr.staging.climatepolicyradar.org/api/v1
        # trunk-ignore(checkov/CKV_SECRET_9)
        BACKEND_API_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhbGxvd2VkX2NvcnBvcmFfaWRzIjpbIkNDTFcuY29ycHVzLmkwMDAwMDAwMS5uMDAwMCIsIkNQUi5jb3JwdXMuR29sZHN0YW5kYXJkLm4wMDAwIiwiQ1BSLmNvcnB1cy5pMDAwMDAwMDEubjAwMDAiLCJDUFIuY29ycHVzLmkwMDAwMDU5MS5uMDAwMCIsIkNQUi5jb3JwdXMuaTAwMDAwNTkyLm4wMDAwIiwiVU4uY29ycHVzLlVOQ0JELm4wMDAwIiwiVU4uY29ycHVzLlVOQ0NELm4wMDAwIiwiVU5GQ0NDLmNvcnB1cy5pMDAwMDAwMDEubjAwMDAiXSwic3ViIjoiQ0NMVyIsImF1ZCI6ImNjbHcuc3RhZ2luZy5jbGltYXRlcG9saWN5cmFkYXIub3JnIiwiaXNzIjoiQ2xpbWF0ZSBQb2xpY3kgUmFkYXIiLCJleHAiOjIwNzcxNzYzNTcuMCwiaWF0IjoxNzYxNjQzNTU3fQ.BOk-adcpkXy91UsEbjEx-aDeYF-ivNFTgCiht9JJOoU
        CONCEPTS_API_URL: https://api.staging.climatepolicyradar.org
        TARGETS_URL: https://cpr-staging-targets-json-store.s3.eu-west-1.amazonaws.com
        APP_URL: https://cclw.staging.climatepolicyradar.org
    ports:
      - "8080"

  navigator-frontend-mcf:
    labels:
      shipyard.route: /
      shipyard.host.mcf: '{"prefix": "mcf"}'
    build:
      context: .
      dockerfile: Dockerfile
      args:
        THEME: mcf
        # trunk-ignore(checkov/CKV_SECRET_6)
        ADOBE_API_KEY: f27f373000c74f22a7f3976caba43efe
        BACKEND_API_URL: https://cpr.staging.climatepolicyradar.org/api/v1
        # trunk-ignore(checkov/CKV_SECRET_9)
        BACKEND_API_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhbGxvd2VkX2NvcnBvcmFfaWRzIjpbIk1DRi5jb3JwdXMuQUYuR3VpZGFuY2UiLCJNQ0YuY29ycHVzLkFGLm4wMDAwIiwiTUNGLmNvcnB1cy5DSUYuR3VpZGFuY2UiLCJNQ0YuY29ycHVzLkNJRi5uMDAwMCIsIk1DRi5jb3JwdXMuR0NGLkd1aWRhbmNlIiwiTUNGLmNvcnB1cy5HQ0YubjAwMDAiLCJNQ0YuY29ycHVzLkdFRi5HdWlkYW5jZSIsIk1DRi5jb3JwdXMuR0VGLm4wMDAwIl0sInN1YiI6Ik1DRiIsImF1ZCI6Im1jZi5zdGFnaW5nLmNsaW1hdGVwb2xpY3lyYWRhci5vcmciLCJpc3MiOiJDbGltYXRlIFBvbGljeSBSYWRhciIsImV4cCI6MjA2NDU3MzYzOC4wLCJpYXQiOjE3NDkwNDA4Mzh9.RtsObc9dH9aSNA6JYnsWuGMHSUHhtkyiZ0707-cA9Hw
        CONCEPTS_API_URL: https://api.staging.climatepolicyradar.org
        TARGETS_URL: https://cpr-staging-targets-json-store.s3.eu-west-1.amazonaws.com
        APP_URL: https://mcf.staging.climatepolicyradar.org
    ports:
      - "8080"

  navigator-frontend-ccc:
    labels:
      shipyard.route: /
      shipyard.host.ccc: '{"prefix": "ccc"}'
    build:
      context: .
      dockerfile: Dockerfile
      args:
        THEME: ccc
        # trunk-ignore(checkov/CKV_SECRET_6)
        ADOBE_API_KEY: f27f373000c74f22a7f3976caba43efe
        BACKEND_API_URL: https://cpr.staging.climatepolicyradar.org/api/v1
        # trunk-ignore(checkov/CKV_SECRET_9)
        BACKEND_API_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhbGxvd2VkX2NvcnBvcmFfaWRzIjpbIkFjYWRlbWljLmNvcnB1cy5MaXRpZ2F0aW9uLm4wMDAwIl0sInN1YiI6ImNjYyIsImF1ZCI6ImNjYy5zdGFnaW5nLmNsaW1hdGVwb2xpY3lyYWRhci5vcmciLCJpc3MiOiJDbGltYXRlIFBvbGljeSBSYWRhciIsImV4cCI6MjA3NDY3MDE3Ni4wLCJpYXQiOjE3NTkxMzczNzZ9.jjAsOCFKVAznxAtsQFj0wozuRmKozy8olwPNyCVAhJk
        CONCEPTS_API_URL: https://api.staging.climatepolicyradar.org
        TARGETS_URL: https://cpr-staging-targets-json-store.s3.eu-west-1.amazonaws.com
        APP_URL: https://ccc.staging.climatepolicyradar.org
    ports:
      - "8080"
