config:
  frontend-faro:grafana_cloud_access_policy_token:
    secure: AAABAM1toxccYVhrppQHCrF7Y0WyE0eqzHoHuXbRIBAGStVwHLbxiU7oc8A3GfEB3I7IX7sVcE1FPg49U0Ei+IijR+AEjl19pqqPrx1kCyEMd6IcRc4k5KpesXXkbyG0o3lCdgwJoBJErQdHj05OHWuiwofNym+X2GTVT3i26Q7dmTI0bURNsGeeoARC0QeeZHb/H1xiaiaYVgzoqfOmZIZq5CSIqDXa1kAdsM3F3mC003pUx26oyMjddkxbZHhJ5ntPONbOIVdJX8OR15nD2ttbx1v9uKOMitl4U4+I4y0U30lLiRgQ8jbqt7/Bu3QUKVnw9w==
