config:
  frontend-faro:grafana_cloud_access_policy_token:
    secure: AAABAHDwnXCQ/npkehC+DWhxS7pFUVvnwrpGi/ZZQSFcxGwxrimgCFU8b9fbSb+LpIpLPAIDw1GKdI2fuzFNg/DoDNfCUH/ldpxA7zedNj8nnvpT36rCzocEC4VhvmuiLxCp+m8llQp4azfvq0HVPp1eRI87m22QGA+7iXGt1VVrxE+qDEI+zWm0IV7bbhc0JAfQ4NQ6cNxuUIpFDHQYl/Tkh6zJVZNSDwG32P46LIPpIGGN5t6JRwbT+VpUB0g4y2fcKZ90UpXwrQFssGgOu5kjo26vNt305yqfZOw4e8NpXjXNniWxARpy34lPTYa/YWsBCg==
