config:
  aws:region: eu-west-1
  frontend:adobe_api_key:
    secure: AAABAFI2eoe1s7VM4xNCk12KIkkO/NJMr185DoF9enGwgbhd8Kxq41cIi8B+jeYJJF4L7tY56cq/erEhfNYsiA==
  frontend:apprunner_frontend_max_concurrency: "50"
  frontend:apprunner_frontend_max_instance_count: "10"
  frontend:apprunner_frontend_min_instance_count: "1"
  frontend:backend_api_token:
    secure: AAABACqHakq91fiBtvU7WMECRuDyFt44WCpuCck2biO4VFYA3P7wHEW5RtTqBlWsp63nku76z4m/zUCU5Ka46MCKtnqNd+D4pMcKlRJdAU7F8rdO7GhAzGNLlmRKx27r02wkLwTDizuPyQQEarFtqTBIlCaVX1Es7fhjhY3MgU5V02D1eHTQbwTVmEmPzmqet6VpZ04gbaddGhnf2vTTgLDMvX96+awujH7Gd2YIOaVJx+Z8x44WxODKmWFIQy/AdmmXAbEOpnP3GZoiSGcWGXpZwrqKEJTfV34jYaISmr/J/8i+TN4pZH8sv3qWoctIQpaGnNc38h+r4j9Xowsg2MELgrAkUQ8r6N84grUJYFmQ8cWqueKCbnlf+bkKdfgJGHlathDxqi5sIlhI1ugC8n1QUEs2WTINrfIvGE3Sm1sK1CQwSPZjDKf2oqCpnxOcO3KVUAluVWqnBNCMg/PY5Oc/ZznmNX9Zr0NVd3NeT00KDw55myvd8q29c5LeyJO0zHeM6pFvSJKHfuLS92uM8BYvDdHVHZJ7pCGl5EvdEhKq7NrvMM7QMMK5Afa/6IO/tmZZHxl8agG3RlyE3QKicNK3pc0SvX1Cgysyy6/Ojph0syo2VBotts0Z3X1DkYm73pPSpURh4W+4RUPJjvi2p8sEhP/NEu4skajfUEgonwJ3FNEOUs9vVsrEneCwBqzPF03/HZPgY07PwCzKhBEePz0kYnIxDRzJX7IGkbUBZzoOeh1rcpOuL8mvQF1Ddf+ICyBcjDX77lnMFUelm+xZ1hColsw0zdaav1ACh8IiaWwcXCZX7tEC5Hm5VajKqIeJBO58l29lOdf7S5jkcFeacgDPvNEqIApg0atxXj4Jr07WUISNTFtA8vcfRdJDGCbFKZ0U63fygRX4sjVWK0hDKt7QhgseU/5TDJSxeBSB+8gG8kcsz5ojhso5qBXdCS0JIgywXEo46JuUdAtPsorgdVLzglgWY4FwPdeHhfDI/shT12gxNJ+nsCvOfy6ta4VL2IBGMrHROFlGRleugygOxfEFxrsdx/XU3t7bLPnOF1+jbWoWXTKiCDfzO0MEj+tzpYAed+mqwobyW9zzxJwJg74KVQGxlhEOtj2j1bPN17ssTchcC9CIn4XWk/ER+voOMvVvpDlRHB5NnE+eR7H/8A7h/uugO25FHkPSbHYN8GtokKe2tbWe3nzspVut0iadSR1vgCt+9sOCLjDe2kRAoJIsqACsga1cCXK6zrME0zhW2Ob1sP4spmMF01aTjG7aRmh+ezSN66SHc5l8q5q1Bsun0GpT7G1OIYYQqhYNV+Tt6GyoY/0D8Kjic8oRIEtp9GKNQoGK8uolbDaMcpEgczUqnpPBSM7xbo/TG+PsddewwcpOWhXr5dCQ0CTUVQwq3q2GXthzK+g34C7HrU584gI=
  frontend:backend_api_url: https://cpr.staging.climatepolicyradar.org/api/v1
  frontend:cdn_url: https://cdn.dev.climatepolicyradar.org
  frontend:ecr_uri:
    secure: AAABANtwLksTlAxxiBTr5jcJlc2Zc5dUFZOoFXa+qLn9TAjDK51scSKmvboH73dZMz3OpJf7l5sCOd5g4PufCq3oVS859x34/1fCjEh3xPN3DJFn8FP3xQ90SN6i7p47XQkn
  frontend:app_url: https://cpr.staging.climatepolicyradar.org
  frontend:redirect_file: default.json
  frontend:robots: "false"
  frontend:s3-path:
    secure: AAABAAnLhbR+eERLbDpxQTrShos90dLDoLJ7mAEFpd1MUz6VUFgk3V0EPQgSqNJofhMsppRQyzK7FWXINRKvl9TlwKRZxMp/31hnjZr+rLkwwP7Fho0kM0gzfNsqzcZbxw==
  frontend:targets_url: https://cpr-staging-targets-json-store.s3.eu-west-1.amazonaws.com
  frontend:theme: cpr
  frontend:validation_account_id:
    secure: AAABAAsNmT1Lfgw7oo6VIDBpHfcvi2LAXULjDmvGjjBzpqmDcPehKt1Esug=
  frontend:concepts_api_url: https://api.staging.climatepolicyradar.org
  frontend:next_public_faro_url: https://faro-collector-prod-gb-south-0.grafana.net/collect/74f6d4bd78b7bb2cc270036193aaa3a6
  frontend:next_public_faro_app_name: cpr-frontend
  frontend:next_public_faro_app_namespace: frontend
  frontend:otel_exporter_otlp_endpoint: https://otel.staging.climatepolicyradar.org/
  frontend:otel_exporter_otlp_protocol: http/protobuf
  frontend:otel_service_name: frontend-server
  frontend:otel_resource_attributes: service.namespace=frontend,environment=staging
  frontend:apprunner_frontend_vcpu_count: 1 vCPU
  frontend:apprunner_frontend_memory_gb: 2 GB
environment:
  - frontend/cpr-staging
