config:
  aws:region: eu-west-1
  frontend:adobe_api_key:
    secure: AAABAEYtB/jafju+i0ihsaNrnt4uMRQK9AmVcvvS+3VoNFJ15UvCgyQ7M+gjZP9daPFoIirVsTv1JqiQUK11MA==
  frontend:auto_scaling_config_arn:
    secure: AAABANp2+MsBWZohjHXJCCAP1rQdlu4TxyyU5RXRUD1NXHjDNSbTCm5sOF5Riwk7nAT1asvrzz+DAs4bvNn7flReZJ0REzNIOkkLiVFjd3Kz0zqefZyRy0C7vfGOh/FgHnp60E3DINtistBUwiKoDjxoM1/NWXur4OGRVd+V4vFCBY3TYJvU1H1QJ9Rwfu75dtp8FhW/0b0=
  frontend:backend_api_token:
    secure: AAABAGZX2uaer3Ygj/O6I9uyoEquxx48jPwV9y2+tP1ijU3JyO2YhSjQv3XsxzWvS4g4si7NCGIZ8HlUGw2kUObK4X1XxPSXZqOeyrNo8OX2BGI3B/0liv9+kIOZY3LXh/qTyS8T4YdJsaXSwMZ75gx+hmpZhGzRd0kWc79/wl2DPKJ8ophm9FC4R4lyUF9vD/nefqE5/8QY/fZfcQzGjKLd7xJ7pwCVleqQ4w2i4r6yGZo8cfQWymgKuoeqwn7g1zV2fdfVEY6WHEoijHbaSaipKt0JM8nGHXVikH2tDxAJS4JfoHKjg4ALE4iuHrq/2b8lJD5/uIoBC9puVzVqD1hUK6oHvk2qzzkzRs6lB5fNFr3z4pn3URX7btyRw6/NsgTCpu3Eq4PxrPp9fLXKeODjSiBNPZqyfDiKr3xaBeKkkoCNyxI9uDvbl+4wEJ5YgLVwdhxg2eH9+Dn1v9WI8lXUow0i0ldy6heRKLdPS8Ow4J3/skBIHj+r067BV5cQcDoulQ4T95n369pqNKsjagkaTymONn8mAWlOk8I4lNd00TW49+ajCUp+4B+57nCpk0MSA0qGmPRb5JCGIrSi/AxsUHFeycE+irULrZqPUBqupDaGAg39bqHyx9phBADAyG+10S3WbZuI7eMySsrkvRDVzfkq4BjJ6wltvLlMEpGSlNMueCzHsWuvZ52pN2r4XaSQgn9RThdocBcHCs+sopfjjX+TBSqd9C+wHFFNtPfURRyVyQ==
  frontend:backend_api_url: https://cpr.staging.climatepolicyradar.org/api/v1
  frontend:cdn_url: https://cdn.dev.climatepolicyradar.org
  frontend:ecr_uri:
    secure: AAABAAirsNpwLRxG3Lns/7197aZkhsVamEurPXbEZbbCcs9+rrUyIxHK/g0Z2/NW2AC97B8/jTsUjOlwZ4rVjYgU7IO3L9lzPkk1QXjLc8vfgIP0f+3ESz5RkjfDroytGSC4
  frontend:app_url: https://mcf.staging.climatepolicyradar.org
  frontend:redirect_file: default.json
  frontend:robots: "false"
  frontend:s3-path:
    secure: AAABABJp5AWzwXjDzNA9yfTHDNfs5hgG6Rg5CEkeL+KcFD9d9oJ38LMps1oNCYtZhV9pWL3seQd2gKTKwBdx+o8Ph8JA4b0+g6g5XZccDKycUpazUyGDP0WGioRy7Cke7A==
  frontend:targets_url: https://cpr-staging-targets-json-store.s3.eu-west-1.amazonaws.com
  frontend:theme: mcf
  frontend:validation_account_id:
    secure: AAABAPD1SMTQPKIwvq1MwDIKBH5AQgQQw8otZ7bmqWBZJYUEWnT9SbITgTg=
  frontend:concepts_api_url: https://api.staging.climatepolicyradar.org
  frontend:next_public_faro_url: https://faro-collector-prod-gb-south-0.grafana.net/collect/74f6d4bd78b7bb2cc270036193aaa3a6
  frontend:next_public_faro_app_name: cpr-frontend
  frontend:next_public_faro_app_namespace: frontend
  frontend:otel_exporter_otlp_endpoint: https://otel.staging.climatepolicyradar.org/
  frontend:otel_exporter_otlp_protocol: http/protobuf
  frontend:otel_service_name: frontend-server
  frontend:otel_resource_attributes: service.namespace=frontend
environment:
  - frontend/mcf-staging
