config:
  aws:region: eu-west-1
  frontend:adobe_api_key:
    secure: AAABAMhyvEAv5wWr7l0OZqiVvN5JwQaf9hn4bixWlteBkYJ1sSpO427fXHCfqsjZWaueSawi18e+DBCeneBOzw==
  frontend:app_url: https://mcf.staging.climatepolicyradar.org
  frontend:auto_scaling_config_arn:
    secure: AAABAInyCfSNaytUn6/SDVtHR8A7sSU9+B6R4HMpUMdMkpXPmtKWM7lMw3kb65+bhXvPa2Neq4ot1IIjuoubeFkmzs7f0kT6QRO8tWMY+QDiaDfEecn1dX4L0hgPDPd7bgzFOOSdNYacOJ5h6JsDKZyoTngrQXTmGLdHc8/MIZbomcXwMuG46yqyMjHbxgcmIlLxNNbeg+o=
  frontend:backend_api_token:
    secure: AAABAPvTMFMVqeXz5C3wSQCZwOM5YH0z0G+cI+aJ3W5tcZDs/6bd+puez2B+G3senQIGvcVdrj7ioItp4MwwSQMZZI9aV3eAEMhF3ipJvEQu2CeZC9Baud/n6mnrtium6rW0HGZWFUmFTsBKYIyyd8A6U9IN2YHEJRd8NnVUNnH74MrI0OaHcq201ui06WkzCUpPYmP15P1WDJXIlw0WsZOHbfKRpB5BGWjdv3CvZ3JRjG9sxJ6wjSuHaDAC5pGTEXMrsS5JcXaGrEMcwqkEPsAgrgps4rdO9GVHdoIRKoEniCFBpWrWDbus+G8K080arqT3oN3JRxhfXv/GOPJrQtj4jGyzzguN3UrnZAM/KCk9zflgvfeaIE9ZGOnRWumdoBaN1jyY5SG6xDg8DtNJ8Esn8yXlNR7HPnEaTOcBVAC4ze3HYXoO+JtRHpbHbZffjFSM9ZmVfXQ2wA27Izy7D20D0gdJ/kAhZblgAErcb0Z7yEOVkmK3hevE+i1T/DAxjdvDpBvNbkyRemdcOess+szrPbBaNUyi9cgJHJIw+5NBA3rjhBPPCLvwdGNKKKMxM7K06HIDimNjjgmtRLTnMktG8O5zIHJ3w/gNkYm6rvuKfVYUCqvdkHQEKY3i+jUrDgV7M0xG99tdAQqzxETu2ujNwy6tbMQ8ouace+hXc95Go7BhLKdfoEQCAegoWImaoh1kRQBHbDSZiNEUkk3LR43UaTuYSUPmbFDWl+Vad3ra7Tk7Yw==
  frontend:backend_api_url: https://cpr.staging.climatepolicyradar.org/api/v1
  frontend:cdn_url: https://cdn.dev.climatepolicyradar.org
  frontend:concepts_api_url: https://api.staging.climatepolicyradar.org
  frontend:ecr_uri:
    secure: AAABAHhp9b2OSN27SuOFYnOsOtR8X0DOr5fOtglpLmBgb+ceQ9pUplfqcMyxi1LpGGNXTINPq6XEU7XEywv4rLQBYfFAWJm3V507cdN/2ZDIyFT+MR84dv/1mUY5601mTG30
  frontend:next_public_faro_app_name: mcf-review-frontend
  frontend:next_public_faro_app_namespace: frontend
  frontend:next_public_faro_url: https://faro-collector-prod-gb-south-0.grafana.net/collect/74f6d4bd78b7bb2cc270036193aaa3a6
  frontend:otel_exporter_otlp_endpoint: https://otel.staging.climatepolicyradar.org/
  frontend:otel_exporter_otlp_protocol: http/protobuf
  frontend:otel_resource_attributes: service.namespace=frontend
  frontend:otel_service_name: frontend-server
  frontend:redirect_file: default.json
  frontend:robots: "false"
  frontend:s3-path:
    secure: AAABAJ6v0Y4tcS9f6nbstBA/vRYGzXrn7MoT59aCWKO+TImYA1SDME9B//QbTarjk5huLasS86SoQImowaa25AEdWIog4H1cB/WYM2TcymxXOosUI3JkVhT2IUrBPGxiQA==
  frontend:targets_url: https://cpr-staging-targets-json-store.s3.eu-west-1.amazonaws.com
  frontend:theme: mcf
  frontend:validation_account_id:
    secure: AAABALb4+jGsEUpV9cPzWOpYfckqJ9axpWmmIy4gNI/7MGuRK0rsW1nf9UE=
  frontend:apprunner_frontend_vcpu_count: "1 vCPU"
  frontend:apprunner_frontend_memory_gb: "2 GB"
environment:
  - frontend/mcf-review
