config:
  aws:region: eu-west-1
  frontend:adobe_api_key:
    secure: AAABAFI2eoe1s7VM4xNCk12KIkkO/NJMr185DoF9enGwgbhd8Kxq41cIi8B+jeYJJF4L7tY56cq/erEhfNYsiA==
  frontend:apprunner_frontend_max_concurrency: "50"
  frontend:apprunner_frontend_max_instance_count: "10"
  frontend:apprunner_frontend_min_instance_count: "1"
  frontend:backend_api_token:
    secure: AAABAFqnd4iIjMHvDkzJJlJDYumczi11JCmIc4PI87l9Ns/LVR6yBjrjenGkDahNJCGId5K2RGZOA1FxjTECYZRzrLLB0UWE9/x2BsTiLqa5tLMvey+n1LfWmmhh36aYBDmnAsRsh0QXnJsbByhSs8qCEAwH9po3/PsJW/ADuKHJHQpIm+Dg3Siib9yW5YGZHKPJWSAHGZnHFww2WPW02FGrbYX1bkal8W7Q4ZdzAHIn/uzN9mMTPiKHdhb7vMPie6Y5pxZETfKj/D5cRmdbV1luKJe+X+hTO4vb5rwlpxZpD6Rc2jkaB6NrWSCU2O7AGwmbSv9y6GROxJjU4lY/TCTz/Pisbw5EgFFvYxvxJ7qzTgI0EojFfldYxd1+bL21kbP2rGn9PmqD61nvQkfwtdQXLR0niDKDkyEraXDTzrCUQoFADGjPDneA/3NkZySuz9zx45Y48rssk+hqhUDSvrR6IwZdgrjrwBE5ikR+eHY4GqB2uppoasusn368XQzAVCSp9LnJj6rBCRpCZP6RRbnrbMbYh7ZLeowUA61S1+QhVcYLSp+VbUqkJkytdiiw/MDAv+ii107O2+tl0L44W5sddap2LYVDSprw7xMBezuPKe+/Yp70VSnmf09ATSXfGP9QKKFS4zju9eHtjqx8+tbZ7h75x3DGgnqbY4HfAe5DXF8N9OxOPY1kYHE7CTTNUwChelmIR0VXCZZ7xU3epEsxnTcSRVagzpe+YGwT2FjsX/W6BuEASCE1oAsfzMTTA74V8R42GbDGZEwQgHOL4akjeud1oRwdlJ5LdAvppazxKLNdt+Zwo8OPk1AYkbigpIEdAT0JeqdjMqTR6D0qKeCFbNfHFxVakLUdvSIynaDyq65gpaASC8KvsRbMOMG2ZmLinXOj58O4FSenL2e766pfH7BMR7g6JUyH3XApcHJiUlqCkqlmG5ZZljq8KxXLPJvZh3O0QZ7+jRXwPHQmsttx1Jy/LbEjtXGKbnnKfwDUJEpFwXcFoWW+dN/uXlDXpuYfIrhSvXLVNaVQ2Yq1RWI/eVbOj5RF7KDTeemTA0aVApJ2dktYhraMG/GVClHidKcwHgNTwK0UKvdnZF7GK7wmr2rf3c54sZH29Pg43mexUfGAxrsNOiwF0GhqB6gD7m1r4zxk18OKjU00h0fwb6cyTNxS1lAN/mYG8QHtYj6/HFmT/3ZL8JElB9RRhNtBMBwmVhU5z071uNW2aaYt/Jw6YCoF9+Af6AirOFwapoulmkxfWu94vT++4b8/F9xOI78NQ2JP+LWN84St86AWpa2AbZK8LoyooBPfQdO3CF7NJkyy5aqAv3DEl7JUrjE8ENosV9mWrvw=
  frontend:backend_api_url: https://app.climatepolicyradar.org/api/v1
  frontend:cdn_url: https://cdn.dev.climatepolicyradar.org
  frontend:ecr_uri:
    secure: AAABANtwLksTlAxxiBTr5jcJlc2Zc5dUFZOoFXa+qLn9TAjDK51scSKmvboH73dZMz3OpJf7l5sCOd5g4PufCq3oVS859x34/1fCjEh3xPN3DJFn8FP3xQ90SN6i7p47XQkn
  frontend:app_url: https://cpr.staging.climatepolicyradar.org
  frontend:redirect_file: default.json
  frontend:robots: "false"
  frontend:s3-path:
    secure: AAABAAnLhbR+eERLbDpxQTrShos90dLDoLJ7mAEFpd1MUz6VUFgk3V0EPQgSqNJofhMsppRQyzK7FWXINRKvl9TlwKRZxMp/31hnjZr+rLkwwP7Fho0kM0gzfNsqzcZbxw==
  frontend:targets_url: https://cpr-staging-targets-json-store.s3.eu-west-1.amazonaws.com
  frontend:theme: cpr
  frontend:validation_account_id:
    secure: AAABAAsNmT1Lfgw7oo6VIDBpHfcvi2LAXULjDmvGjjBzpqmDcPehKt1Esug=
  frontend:concepts_api_url: https://api.climatepolicyradar.org
  frontend:next_public_faro_url: https://faro-collector-prod-gb-south-0.grafana.net/collect/74f6d4bd78b7bb2cc270036193aaa3a6
  frontend:next_public_faro_app_name: cpr-frontend
  frontend:next_public_faro_app_namespace: frontend
  frontend:otel_exporter_otlp_endpoint: https://otel.staging.climatepolicyradar.org/
  frontend:otel_exporter_otlp_protocol: http/protobuf
  frontend:otel_service_name: frontend-server
  frontend:otel_resource_attributes: service.namespace=frontend,environment=staging
  frontend:apprunner_frontend_vcpu_count: 1 vCPU
  frontend:apprunner_frontend_memory_gb: 2 GB
environment:
  - frontend/cpr-staging
