config:
  aws:region: eu-west-1
  frontend:adobe_api_key:
    secure: AAABAAi2JxgoL69p29mS81jMeN9HW8NXtNzey9tLc04J50MxvZVY5maA1urn5/xPP7+ItbbfO9uSkYnvZnA4hw==
  frontend:backend_api_url: https://app.climatepolicyradar.org/api/v1
  frontend:backend_api_token:
    secure: AAABANJs3n8oHEkIp13yP6eCsJZpE/iP+nkQBwcUqm5np6o0NNpNPcZIQeafWhO3Iq6X5CUwyU5F+fNnB6SLjTenYUJgCt8Yrw88LKMnQ0Rhz2USvNGDm3XCt4uh+/Vm9kZW6sV+Zlz9repoPMgvA6BxAOCuS01HASJI7+zH+TL4WEyHY/asEbRMafkEmmac1wbrS/pzjKgmo3wXSVTomPMOmSQycOcULC3fsQFwVkQ+W7oBVU7XgH10zFodUlOGt2A8XJgUCIO5gRFql0E2uo7k1Sb/fq1NoyNfeSDAUO0UsdhXUFycg2hbUSAZ4pd6kFg1ypOOUkwhD+UrKwp/cujctxcsel9j0i+vTLH2L/UXCvUjuzkcZK3XaDYFDSBRrG+4Y9QZsv91uI+DgVrKo23apKjrXvdUupDAx5DilJVNsDMU4Jptmrn2OxLzsM9HyvUupTAe75ukdADR3I730tfhdpxZNlEss5c1ZLV/4VfCN8vevspvyu37+99shTbA+mc8RfVpDyb1YSp8moGtpYdBz5w59jVrJhquD176wj/3H53CAOeYJhRyR6nARRiNROtq/Y5rCpY1ILetRmVE7R8HksN2c/tWfI2XwBv+SOCXCi6SbVDCj33a5f5+2wRJkTx0wiNUQGXt7QlGaR0FMyOvMUtGtOyIYSdWFIe/4T2/V2PIoafv2suxppD+1HIvx7oUS6Ty57zjxsRAtinjBfb9LrKf9QHe3EKjpHLXp/yVjdsaisf1jfYCDgNueTnjeg9P0ohl3ayNvvxbi3X/4QAgBl50vJLUuTQgfXvqjAE764NB9KO5V+VjQdTcw7HrRKwpywI+rRirEOUfOITCMVPqfHbLSmNEHc8PihjclL5yt47ea1+Opq2VWIxQmyZTq8inpjPmjydWn0351YPvMUYmzocZbkvI8Uy9fdoZF3f9Hwe8Ky5CGNX2mN9W/SHK6hYV1ZT4EFAPGljDWGFLtXQE+rn29l3chE3LcaaxHXE4WJI/yCZPKC7sXAf7h+FhPOBS6hVAytcJPNUTujvPEF5BVuJq4UqudEDqmhra5pvPIgRQQSfRZzHpbdFi9tguzzjw+9sjt5NB8+aCAqXsKrBpJ8mQL1MmFHeGJMUTCBdXtMpOtw987RzIKkSEy0ejTaLJCRqw22M4BtHjYWDml1Wkrz9TVnsXJESwQ4n9bTA8/7nz1IIXQS11UFI4eyKZL18JH2W8Wvcz1Qr8yJhqzhJ2Xt2ZlzJ1va5Xlig8fjNuht/Gsekhou3Y30jjRGLjfo/jrB52pwYiwgEKOjp2wqpQYqdm5YdNUfATgdvglhphuR3nNujnGlK7BrkdozaGWY/PMYEbV2U=
  frontend:apprunner_frontend_max_concurrency: "50"
  frontend:apprunner_frontend_max_instance_count: "10"
  frontend:apprunner_frontend_min_instance_count: "3"
  frontend:ecr_uri:
    secure: AAABAN+5OXYAifqQ9hO6Ko/qNNbnIs3k2FEqSwAB7ZDcdRR15bs9TfVloAOilaTHKOKOUcmwl57hKcwPCRO1tBkpI6Ewsckn+hOBICmsYAmO3kAVjkWct/bHvpQUUz55PBKs
  frontend:app_url: https://app.climatepolicyradar.org
  frontend:cname: app.climatepolicyradar.org
  frontend:redirect_file: default.json
  frontend:robots: "true"
  frontend:s3-path:
    secure: AAABAAadDO3OJ51xGJ0MANP3gS9gULW3n+s0AwQKBhgyi6NltbfHtI+0mPI2m4GehCqMCW//FohsUh8cT1VtcwFqgV+/ivHKcOGgKhVPSCnTExK4QKLtz39oox/gEtH/8KumHQ==
  frontend:targets_url: https://cpr-production-targets-json-store.s3.eu-west-1.amazonaws.com
  frontend:cdn_url: https://cdn.climatepolicyradar.org
  frontend:theme: cpr
  frontend:validation_account_id:
    secure: AAABAKctmQ28pLTMUXWpOn7O6diir8MHUrdkArq6l3+QXpNP671XHBBTnVs=
  frontend:concepts_api_url: https://api.climatepolicyradar.org
  frontend:next_public_faro_url: https://faro-collector-prod-gb-south-0.grafana.net/collect/74f6d4bd78b7bb2cc270036193aaa3a6
  frontend:next_public_faro_app_name: cpr-frontend
  frontend:next_public_faro_app_namespace: frontend
  frontend:otel_exporter_otlp_endpoint: https://otel.staging.climatepolicyradar.org/
  frontend:otel_exporter_otlp_protocol: http/protobuf
  frontend:otel_service_name: frontend-server
  frontend:otel_resource_attributes: service.namespace=frontend
  frontend:apprunner_frontend_vcpu_count: "4 vCPU"
  frontend:apprunner_frontend_memory_gb: "8 GB"
environment:
  - frontend/cpr-production
