config:
  aws:region: eu-west-1
  frontend:adobe_api_key:
    secure: AAABABgAfsK3k3qDfj8hm4TuoRS4SMjX2DTEPBpfLCWnD/8KjOV4kq1Z/pxTk5zZ2bq9rUI677ngpoKEHEI93Q==
  frontend:app_url: https://app.climatepolicyradar.org
  frontend:apprunner_frontend_max_concurrency: "50"
  frontend:apprunner_frontend_max_instance_count: "10"
  frontend:apprunner_frontend_min_instance_count: "1"
  frontend:backend_api_token:
    secure: AAABADtQY8DqMmHnzB3IawMsTzSAm4Tp+ev9ZvfLoH599d2PNeQpkDnv57Tuwf9QjdPIfQ1I8oK5M/mVMPWjTse3xLlOWSrPqfZZJG96BIS9Xh+Ai/j/C+SmWXeSN0xlwHrnOEGQGYgupA8vxf+nWFgp5Xz1qhNyUbKtcUAnR0q64Z6SUJb09qSWHOaTh5iXbhVnTkDki4qt62xMPY8jTnYjX2DpE2ArngbSm7pym8y5Az59EWmkGMF/O9DdAX9eRGMWjOiT7xybx7gMh/N01je8R6Cpiyda3hvsI2O5n3gg1yOO9ozyK7zH1ArvEbbIHGWdKVSmbBCbgRidDY0lsCcNM0Eu9OoKhgNF3K0IrUVfFT2J1pFVOq+58Moez+TFNORcfai/VfrVSRBq0TmJw5Mb9yMiQmIRzjlgYnEZqV0Vldn/aQYQ7WHmKtCrPJqWMqu5jJ1r7DBQyB+fO4R6Zl0cNJtXWA7VUN2li7p29nIw3IW/zyDsvxoARlN0pA6Gm6xwufFRWCkY3MVbZJeo1XUMUk7jebIwrEpCcgq17oT9OQVWvhqgCD16NbD3ZYa9EgpVGnFcIaKQOobr0kRjBFG2uEJmjOgapnUflHKB77akbT6nXpiFHQ7SpG0Uj38Mnt6I6Zxdcgdv2X6R73PDGYdutwLkYWHeTGB8hzSJUAbMF2fQypXsXX9lRTMGHZexcnlaOLlrAOvPRvzlFv/IS33MnllF8nFg46R8LKIBgRoRM5fbZaC53C/sb+OSYpN1//WFqRRTp+nUlNJWmv7nNWu4rwldpW6WzH6wDsxSp4rz57CrkN8aP6KHgqSbvpGmt2Ub0rP8Nbiw/j5Yia3OmuzL8TcrgGZTcgdz2ee4RlilEXeH17xPDxqbFoiVxgXmBCnGdDIaX2M2tWEiuP5rpw7fQUFL3nyZRABHUHl87aDQoqwcXTdb5UuoUsA3otv8+oRMLNrAeX+UHyltfceS1Hkao7i1QlTuVa9Q7NsNMGhGbgURauGMTe+F9JMp7IyUny3jENSsOb+JTYn4ukkaywpirwCCZPpwTeSbh4A6CAWarmaMbFHvLVLVftKNpTmXimAVEFNYEZylbOCWq2oxuHHHRM3hYPit9JXiWy03Fy5lZYTlAFpVTJu/YH4Zuz6VXMHMSgUvTBOUchaLqeTMZcP1MsNv/Fm51ZDps48RrF0UPL0hzZ4HeJNTw4v2DQrBvyWlf83JmpnT+AHp+06BLqhcHZGOyKhljx78lSdgwTxS4ZZmjcaRcLkCRPa1t6bVKkgCcwUJnRL+Q42mifD9WIX+NJuHj/rC5sucyhHBa3JIRw0phMl49FKeoDQPt8U8c1EeRCLFJmw=
  frontend:backend_api_url: https://app.climatepolicyradar.org/api/v1
  frontend:cdn_url: https://cdn.climatepolicyradar.org
  frontend:concepts_api_url: https://api.climatepolicyradar.org
  frontend:ecr_uri:
    secure: AAABADDjtmoNtgqV00jpPD4L7ZX6qq3/oeInKnqED2mFYBXI/0biwVA00k7LVS5wkATmnwlzgto4A1HD5LNQ36aqmd7jTL3GczoqnZOJB1D8tiRjgYely0Wu20iN2UyylapF
  frontend:next_public_faro_app_name: cpr-review-frontend
  frontend:next_public_faro_app_namespace: frontend
  frontend:next_public_faro_url: https://faro-collector-prod-gb-south-0.grafana.net/collect/74f6d4bd78b7bb2cc270036193aaa3a6
  frontend:otel_exporter_otlp_endpoint: https://otel.prod.climatepolicyradar.org/
  frontend:otel_exporter_otlp_protocol: http/protobuf
  frontend:otel_resource_attributes: service.namespace=frontend
  frontend:otel_service_name: frontend-review-server
  frontend:redirect_file: default.json
  frontend:robots: "false"
  frontend:s3-path:
    secure: AAABANF6SiGUbnJx0CdB7yUZ+4NbkmfoR5PgtSekEXwj/rrdLwSNF66uml7tO23aB6ZZ++4rCZJfqYHxRUWRqstfWxMkzMRG16lXFq1ywV6FcyGJdw8HjtxO+M8yIzJ4y2yxZQ==
  frontend:targets_url: https://cpr-production-targets-json-store.s3.eu-west-1.amazonaws.com
  frontend:theme: cpr
  frontend:validation_account_id:
    secure: AAABADlaqxzs1q1mw9O94vXRfSPd4ls2AOApUnj5+N51ht2QocH02ToYNws=
  frontend:auto_scaling_config_arn:
    secure: AAABAMaACKo+TYbkmVU000GHeLYFLAujP5Zb4HaBJmtHQJFjk2pOFspl8xsBnU7uYwcFCt1p83sSfDJfS+VDBWAZFfXHznimWlVXPi2wVWKgiq2N3TG2plO16RwExFKnJmkF0wY2uFG9PKJ4y8jUZ1n1SYbpV6MTwYICZx6TATCGWKKvyjbdUoV1jqc6GWc91YVV+I/GQYZFHX4=
  frontend:apprunner_frontend_vcpu_count: 1 vCPU
  frontend:apprunner_frontend_memory_gb: 2 GB
  frontend:next_static_enabled: "false"
environment:
  - frontend/cpr-review
