config:
  aws:region: eu-west-1
  frontend:adobe_api_key:
    secure: AAABAPouucxLN1H/N6UrulYuylDzTUgMdNlBM14oJGQRZ7ImeL8VNUyFzMRbb4QfzSeh97LaURZ6/PG8nKxUPw==
  frontend:app_url: https://cpr.staging.climatepolicyradar.org
  frontend:apprunner_frontend_max_concurrency: "50"
  frontend:apprunner_frontend_max_instance_count: "10"
  frontend:apprunner_frontend_min_instance_count: "1"
  frontend:backend_api_token:
    secure: AAABADTkazG8g5NDWsj2UxhLXtlkzUIbd1+Up398r9/EvLb4GletFxGfnYwFeu7IXyemwKR7EvDfWGrTpp1CRz7SJA0yAQHSTGj+Xyj8lbA+GQ7UWDW8rU0xlMpJynOevk5mnsSR5XIr3pqDpV+bVXEuqdUAf45BCWkdK21+llsmaMcqXMporbncf7mIhFCtV1I6R+cYEiFXnbNuLiRA2UT4Ptbqlh2vpVoYRbeLXiqUyZf/3cBvd3+5bIKRuOxCVC80Fq7YYQ/QJriPKv4A7LX6pRLvyC0MGyMTrzrT0UzUWAp00vdvtXTfO4fPYWakvfnmL1p47QbOs6pAxYD5Rx0iGsvDXkdyoQqD10hGIb2WkLqjQbTE5oKTaeBjlGP/eDSSku/5TLmL8Nfv8qPBMIhm+VaDmswlWc4s9hAHlWWwkt6F8sLR54Mb88iMIGtJeRr6RtbfnxwLnQkLR92v+hKodQuB5jpsP6HJ69octiJz/EIjekLaEUE1ECfdEyO0FjZpvFKMYb8TgW+RLvo7W8cBhOg7Thkq41ZBiGg2awPcyuVaORtUy4c7DGindk2kTgMi9iHsxcZ7B3pmng2T0Nf2epw6FHBOpyNS247sqLEwiv7tupnetRGGu1wXb8yAnd1wHRTeqVMpjjgunf9IRuSJ6x9Q2/rFZhgIvvCikH8LhvgNd4NpdbPYTCkX/atKdtMqKrQd2XI1oSHV1akCX9lcKzR5GZPAmqOsq3jMYfYblzP4MngdY8SNI+3n4bXcUaEtE2EXpHO8zTL/DfShzqswsuAXFmewx1g27DaXks20jaMkSKqKKRqsAFa1+JaheUWf/XKyBoIliAH8t/CGFcUGU/ndHyXN3NnBA9fgmj9ysBJYPW09yXwJouPWhK6ZQDdXqzEsMJwXnGmPoJ8la8ppexZPhlcn7ZU/rx6GMNjUwpQxVYGdaaxeGBo0f4XhT6JpK6O1yFhtkeZfxOJMLsoTaMRsIvTuLJzZ+tOXZ5ncTm3Oyr0HMsQn1HT23LtKNGOOKQIuX+ho4FbF4fLv++wRVGzCPpa/0IOaehFBFgNO1u8w2y+a+I1f01hAl4ulWlOGtOtQV2XZXuPsw91JrycFQe6L2yIsfUtCwM82Si4Dz+T8yIPeCxBr9tnHSi4u7DyPWwLm234OUZU/wQBXsLQsi9VYpf5q4yUsLpn24CnZcHwzUZTgnISUohev1VqiWAEDafW1hlgeWw2XMs9oUby6Nk1dh1oezbKFg0+JalKJAjKovBEfKHT3mwDtbINJincGm8RJ5PC58Jh3LlEWOCj1rIgjRhFn3z5WP5IWEEaGOU8TKKT323UW0gvVt5IEguXND66PqaXGG28lR0JoaW5BHwM9qlUZBw==
  frontend:backend_api_url: https://cpr.staging.climatepolicyradar.org/api/v1
  frontend:cdn_url: https://cdn.dev.climatepolicyradar.org
  frontend:concepts_api_url: https://api.staging.climatepolicyradar.org
  frontend:ecr_uri:
    secure: AAABAIuzBoUU99z6tqfuuzokDk/5hLrxmn6rgXm3hnyVXYIt0f5LCXVZfrn8UosH7Dkh6x+UHoUyQqO4q7gFMZGWGqAOrP14bDK7MV8lILT5dnpMy0URM4EK5OdTtnc6NQ46
  frontend:next_public_faro_app_name: cpr-frontend-review
  frontend:next_public_faro_app_namespace: frontend
  frontend:next_public_faro_url: https://faro-collector-prod-gb-south-0.grafana.net/collect/74f6d4bd78b7bb2cc270036193aaa3a6
  frontend:otel_exporter_otlp_endpoint: https://otel.staging.climatepolicyradar.org/
  frontend:otel_exporter_otlp_protocol: http/protobuf
  frontend:otel_resource_attributes: service.namespace=frontend
  frontend:otel_service_name: frontend-server
  frontend:redirect_file: default.json
  frontend:robots: "false"
  frontend:s3-path:
    secure: AAABAF3XtEIcmHE8QtOatd54CU6k7vNKmf8dx0GdojzxDyEHD362achLY2XcHLllUWn6qzq6ol8GnzrydPdOqU7BCmBY/DvJuFiREEU/NWwOjOWNQ46U7tibVTK5tuOPcg==
  frontend:targets_url: https://cpr-staging-targets-json-store.s3.eu-west-1.amazonaws.com
  frontend:theme: cpr
  frontend:validation_account_id:
    secure: AAABAFTuELjLDYbz/A7MHCgQAvxfwImta8Os7g6EGO2dsM699rEuQrfSs5I=
environment:
  - frontend/cpr-review
