export const FRAMEWORK_LAWS = [
  {
    title: "Law no 155/2020 on climate change",
    geo_iso: "ALB",
    geography: "Albania",
    url: "https://climate-laws.org/document/law-no-155-2020-on-climate-change_1817",
  },
  {
    title: "Law 21/2018, of 13 September, on the promotion of the energy transition and climate change",
    geo_iso: "AND",
    geography: "Andorra",
    url: "https://climate-laws.org/document/law-21-2018-of-13-september-on-the-promotion-of-the-energy-transition-and-climate-change_0fbe",
  },
  {
    title: "Law 27520 on Minimum Budgets for Adaptation and Mitigation to Global Climate Change",
    geo_iso: "ARG",
    geography: "Argentina",
    url: "https://climate-laws.org/document/law-27520-on-minimum-budgets-for-adaptation-and-mitigation-to-global-climate-change_f2e5",
  },
  {
    title: "Climate Change Act 2022",
    geo_iso: "AUS",
    geography: "Australia",
    url: "https://climate-laws.org/document/climate-change-act-2022_ba85",
  },
  {
    title: "Climate Protection Act (Klimaschutzgeset)",
    geo_iso: "AUT",
    geography: "Austria",
    url: "https://climate-laws.org/document/climate-protection-act-klimaschutzgeset_7307",
  },
  {
    title: "Climate Change and Carbon Market Initiatives Act, 2022",
    geo_iso: "BHS",
    geography: "Bahamas",
    url: "https://climate-laws.org/document/climate-change-and-carbon-market-initiatives-act-2022_db37",
  },
  {
    title: "Law on the governance of federal climate policy",
    geo_iso: "BEL",
    geography: "Belgium",
    url: "https://climate-laws.org/document/law-on-the-governance-of-federal-climate-policy_b052",
  },
  {
    title: "Law no 2018/18 regulating climate change actions",
    geo_iso: "BEN",
    geography: "Benin",
    url: "https://climate-laws.org/document/law-no-2018-18-regulating-climate-change-actions_6373",
  },
  {
    title: "Law 12.187/2009, establishing the National Policy on Climate Change (NPCC), regulated by Decree 7.390/2010",
    geo_iso: "BRA",
    geography: "Brazil ",
    url: "https://climate-laws.org/document/law-12-187-2009-establishing-the-national-policy-on-climate-change-npcc-regulated-by-decree-7-390-2010_dd44",
  },
  {
    title: "Climate Change Mitigation Act",
    geo_iso: "BGR",
    geography: "Bulgaria",
    url: "https://climate-laws.org/document/climate-change-mitigation-act_13f9",
  },
  {
    title: "Canadian Net-Zero Emissions Accountability Act",
    geo_iso: "CAN",
    geography: "Canada",
    url: "https://climate-laws.org/document/canadian-net-zero-emissions-accountability-act_d275",
  },
  {
    title: "Framework Law on Climate Change - Chile",
    geo_iso: "CHL",
    geography: "Chile",
    url: "https://climate-laws.org/document/framework-law-on-climate-change-chile_dc8a",
  },
  {
    title: "Law 2169/2021 promoting low-carbon development",
    geo_iso: "COL",
    geography: "Colombia",
    url: "https://climate-laws.org/document/law-2169-2021-promoting-low-carbon-development_add6",
  },
  {
    title: "Law no 1931 establishing guidelines for the management of climate change",
    geo_iso: "COL",
    geography: "Colombia",
    url: "https://climate-laws.org/document/law-no-1931-establishing-guidelines-for-the-management-of-climate-change_08a2",
  },
  {
    title: "Law on Climate Change and the Protection of the Ozone Layer",
    geo_iso: "HRV",
    geography: "Croatia ",
    url: "https://climate-laws.org/document/law-on-cliamate-change-and-the-protection-of-the-ozone-layer_f5ab",
  },
  {
    title: "The Climate Act",
    geo_iso: "DNK",
    geography: "Denmark",
    url: "https://climate-laws.org/document/the-climate-act_dae7",
  },
  {
    title: "Regulation (EU) 2021/1119 establishing the framework for achieving climate neutrality (European Climate Law)",
    geo_iso: "EUR",
    geography: "European Union",
    url: "https://climate-laws.org/document/regulation-eu-2021-1119-establishing-the-framework-for-achieving-climate-neutrality-european-climate-law_df60",
  },
  {
    title: "Climate Change Act 2021",
    geo_iso: "FJI",
    geography: "Fiji",
    url: "https://climate-laws.org/document/climate-change-act-2021_8bf7",
  },
  {
    title: "Climate Change Act 609/2015",
    geo_iso: "FIN",
    geography: "Finland",
    url: "https://climate-laws.org/document/climate-change-act-609-2015_df00",
  },
  {
    title: "Law No 2021-1104 on the fight on climate change and resilience",
    geo_iso: "FRA",
    geography: "France",
    url: "https://climate-laws.org/document/law-no-2021-1104-on-the-fight-on-climate-change-and-resilience_6f7e",
  },
  {
    title: "Law no. 2019-1147 on Energy and the climate",
    geo_iso: "FRA",
    geography: "France",
    url: "https://climate-laws.org/document/law-no-2019-1147-on-energy-and-the-climate_64b3",
  },
  {
    title: "Law no. 2015-992 on Energy Transition for Green Growth (Energy Transition Law)",
    geo_iso: "FRA",
    geography: "France",
    url: "https://climate-laws.org/document/law-no-2015-992-on-energy-transition-for-green-growth-energy-transition-law_aea3",
  },
  {
    title: "Law No. 018/2022 ratifying Ordinance No. 019/PR/2021 relating to climate change",
    geo_iso: "GAB",
    geography: "Gabon",
    url: "https://climate-laws.org/document/ordinance-no-019-2021-of-13-09-2021-relating-to-climate-change_883e",
  },
  {
    title: "Federal Climate Adaptation Act (KAnG)",
    geo_iso: "DEU",
    geography: "Germany",
    url: "https://climate-laws.org/document/federal-climate-adaptation-act-kang-6100",
  },
  {
    title: 'Federal Climate Protection Act ("Bundesklimaschutzgesetz” or “KSG")',
    geo_iso: "DEU",
    geography: "Germany",
    url: "https://climate-laws.org/document/federal-climate-protection-act-and-to-change-further-regulations-bundesklimaschutzgesetz-or-ksg_c1c2",
  },
  {
    title: "National Climate Law 4936/2022 on the transition to climate neutrality and adaptation to climate change",
    geo_iso: "GRC",
    geography: "Greece",
    url: "https://climate-laws.org/document/national-climate-law-4936-2022-on-the-transition-to-climate-neutrality-and-adaptation-to-climate-change_2ff3",
  },
  {
    title:
      "Framework law to regulate reduction of vulnerability, mandatory adaptation to the effects of climate change, and the mitigation of greenhouse gas effects (Decree of the Congress 7-2013)",
    geo_iso: "GTM",
    geography: "Guatemala",
    url: "https://climate-laws.org/document/framework-law-to-regulate-reduction-of-vulnerability-mandatory-adaptation-to-the-effects-of-climate-change-and-the-mitigation-of-greenhouse-gas-effects-decree-of-the-congress-7-2013_6c9f",
  },
  {
    title: "Decree no. 297-2013 (Law on Climate Change)",
    geo_iso: "HND",
    geography: "Honduras",
    url: "https://climate-laws.org/document/decree-no-297-2013-law-on-climate-change_7eaf",
  },
  {
    title: "Law on climate protection",
    geo_iso: "HUN",
    geography: "Hungary",
    url: "https://climate-laws.org/document/law-on-climate-protection_3a0f",
  },
  {
    title: "2012 Act no. 70 on Climate Change",
    geo_iso: "ISL",
    geography: "Iceland",
    url: "https://climate-laws.org/document/2012-act-no-70-on-climate-change_6450",
  },
  {
    title: "Climate Action and Low Carbon Development Act 2015",
    geo_iso: "IRL",
    geography: "Ireland",
    url: "https://climate-laws.org/document/climate-action-and-low-carbon-development-act-2015_2ea8",
  },
  {
    title: "Act on Promotion of Global Warming Countermeasures ",
    geo_iso: "JPN",
    geography: "Japan",
    url: "https://climate-laws.org/document/act-on-promotion-of-global-warming-countermeasures-law-no-117-of-1998_c497",
  },
  {
    title: "Climate Change Adaptation Act",
    geo_iso: "JPN",
    geography: "Japan",
    url: "https://climate-laws.org/document/climate-change-adaptation-act_23ed",
  },
  {
    title: "Climate Change Act, 2016",
    geo_iso: "KEN",
    geography: "Kenya",
    url: "https://climate-laws.org/document/climate-change-act-2016_7078",
  },
  {
    title: "Disaster Risk Management and Climate Change Act",
    geo_iso: "KIR",
    geography: "Kiribati",
    url: "https://climate-laws.org/document/disaster-risk-management-and-climate-change-act_1110",
  },
  {
    title: "Law on Climate Change",
    geo_iso: "XKX",
    geography: "Kosovo",
    url: "https://climate-laws.org/document/law-on-climate-change_15c7",
  },
  {
    title: "Emissions Trading Act",
    geo_iso: "LIE",
    geography: "Liechtenstein ",
    url: "https://climate-laws.org/document/emissions-trading-act_8a34",
  },
  {
    title: "Law of 15 December 2020 relating to the climate",
    geo_iso: "LUX",
    geography: "Luxembourg",
    url: "https://climate-laws.org/document/law-of-15-december-2020-relating-to-the-climate_40b1",
  },
  {
    title: "Climate Emergency Act (Act no. 9/2021)",
    geo_iso: "MDV",
    geography: "Maldives",
    url: "https://climate-laws.org/document/climate-emergency-act-act-no-9-2021_706a",
  },
  {
    title: "Climate Action Act",
    geo_iso: "MLT",
    geography: "Malta",
    url: "https://climate-laws.org/document/climate-action-act_cde3",
  },
  {
    title: "Climate Change Act 2020 (no 11/2020)",
    geo_iso: "MUS",
    geography: "Mauritius",
    url: "https://climate-laws.org/document/climate-change-act-2020-no-11-2020_539f",
  },
  {
    title: "General Law on Climate Change",
    geo_iso: "MEX",
    geography: "Mexico",
    url: "https://climate-laws.org/document/general-law-on-climate-change_14c5",
  },
  {
    title: "Federated States of Micronesia Climate Change Act",
    geo_iso: "FSM",
    geography: "Micronesia",
    url: "https://climate-laws.org/document/federated-states-of-micronesia-climate-change-act_a0d5",
  },
  {
    title: "Law on Protection from the Negative Impacts of Climate Change",
    geo_iso: "MNE",
    geography: "Montenegro",
    url: "https://climate-laws.org/document/law-on-protection-from-the-negative-impacts-of-climate-change_2c3c",
  },
  {
    title: "Law 15/2014 Establishing the Framework for Disaster Management, Including Prevention and Mitigation",
    geo_iso: "MOZ",
    geography: "Mozambique",
    url: "https://climate-laws.org/document/law-15-2014-establishing-the-framework-for-disaster-management-including-prevention-and-mitigation_fc9c",
  },
  {
    title: "Environmental Management and Climate Change Act no 34/2020",
    geo_iso: "NRU",
    geography: "Nauru",
    url: "https://climate-laws.org/document/environmental-management-and-climate-change-act-no-34-2020_942c",
  },
  {
    title: "Climate Act (Klimaatwet)",
    geo_iso: "NLD",
    geography: "Netherlands",
    url: "https://climate-laws.org/document/climate-act_4bc4?l=netherlands&c=Legislation",
  },
  {
    title: "Climate Change Response (Zero Carbon) Amendment Act (amending the Climate Change Response Act 2002)",
    geo_iso: "NZL",
    geography: "New Zealand",
    url: "https://climate-laws.org/document/climate-change-response-zero-carbon-amendment-act-amending-the-climate-change-response-act-2002_abaa",
  },
  {
    title: "Nigeria's Climate Change Act",
    geo_iso: "NGA",
    geography: "Nigeria",
    url: "https://climate-laws.org/document/nigeria-s-climate-change-act_5ef7",
  },
  {
    title: "Climate Change Act",
    geo_iso: "NOR",
    geography: "Norway",
    url: "https://climate-laws.org/document/climate-change-act_5031",
  },
  {
    title: "Pakistan Climate Change Act, 2017",
    geo_iso: "PAK",
    geography: "Pakistan",
    url: "https://climate-laws.org/document/pakistan-climate-change-act-2017_3453",
  },
  {
    title: "Climate Change (Management) Act 2015 (No. 19 of 2015)",
    geo_iso: "PNG",
    geography: "Papua New Guinea",
    url: "https://climate-laws.org/document/climate-change-management-act-2015-no-19-of-2015_42ff",
  },
  {
    title: "National Law on Climate Change no. 5875",
    geo_iso: "PRY",
    geography: "Paraguay",
    url: "https://climate-laws.org/document/national-law-on-climate-change-no-5875_fa63",
  },
  {
    title: "Framework Law no 30754 on Climate Change",
    geo_iso: "PER",
    geography: "Peru",
    url: "https://climate-laws.org/document/framework-law-no-30754-on-climate-change_688f",
  },
  {
    title: "The Climate Change Act (RA 9729), and its Implementing Rules and Regulations (IRR, Administrative Order No. 2010-01)",
    geo_iso: "PHL",
    geography: "Philippines",
    url: "https://climate-laws.org/document/the-climate-change-act-ra-9729-and-its-implementing-rules-and-regulations-irr-administrative-order-no-2010-01_a739",
  },
  {
    title: "Framework climate law no 98/2021",
    geo_iso: "PRT",
    geography: "Portugal",
    url: "https://climate-laws.org/document/framework-climate-law-no-98-2021_2801",
  },
  {
    title: "Federal Law No. 296-FZ On limiting greenhouse gas emissions",
    geo_iso: "RUS",
    geography: "Russia",
    url: "https://climate-laws.org/document/federal-law-no-296-fz-on-limiting-greenhouse-gas-emissions_1d0b",
  },
  {
    title: "Law on Disaster Risk Reduction and Emergency Situation Management 2018 ",
    geo_iso: "SRB",
    geography: "Serbia",
    url: "https://climate-laws.org/document/law-on-disaster-risk-reduction-and-emergency-situation-management-2018_d23d",
  },
  {
    title: "Serbian Law on Climate Change",
    geo_iso: "SRB",
    geography: "Serbia",
    url: "https://climate-laws.org/document/serbian-law-on-climate-change_7d49",
  },
  {
    title: "Environmental Protection Act",
    geo_iso: "SVN",
    geography: "Slovenia",
    url: "https://climate-laws.org/document/environmental-protection-act_1297",
  },
  {
    title: "Climate Change Act, 2024",
    geo_iso: "ZAR",
    geography: "South Africa",
    url: "https://climate-laws.org/document/climate-change-act_6e08",
  },
  {
    title: "Carbon Neutral Green Growth Framework Act to tackle the Climate Crisis",
    geo_iso: "KOR",
    geography: "South Korea",
    url: "https://climate-laws.org/document/carbon-neutral-green-growth-framework-act-to-tackle-the-climate-crisis_fb15",
  },
  {
    title: "Law 7/2021 on climate change and energy transition",
    geo_iso: "ESP",
    geography: "Spain",
    url: "https://climate-laws.org/document/law-7-2021-on-climate-change-and-energy-transition_f039",
  },
  {
    title: "Climate Act",
    geo_iso: "SWE",
    geography: "Sweden",
    url: "https://climate-laws.org/document/climate-act_9e1d",
  },
  {
    title: "Federal Act on Climate Protection Goals, Innovation and Strengthening Energy Security",
    geo_iso: "CHE",
    geography: "Switzerland",
    url: "https://climate-laws.org/document/federal-act-on-climate-protection-goals-innovation-and-strengthening-energy-security_d8b9",
  },
  {
    title: "CO2 Act",
    geo_iso: "CHE",
    geography: "Switzerland",
    url: "https://climate-laws.org/document/co2-act_9e7c",
  },
  {
    title: "CO2 Ordinance (2020 Provisional Version)",
    geo_iso: "CHE",
    geography: "Switzerland",
    url: "https://climate-laws.org/document/co2-ordinance-2020-provisional-version_88c1",
  },
  {
    title: "Climate Change Response Act",
    geo_iso: "TWN",
    geography: "Taiwan",
    url: "https://climate-laws.org/document/greenhouse-gas-reduction-and-management-act_1357",
  },
  {
    title: "National Climate Change Act 2021",
    geo_iso: "UGA",
    geography: "Uganda",
    url: "https://climate-laws.org/document/national-climate-change-act-2021_aeec",
  },
  {
    title: "Climate Change Act 2008",
    geo_iso: "GBR",
    geography: "United Kingdom",
    url: "https://climate-laws.org/document/climate-change-act-2008_47b4",
  },
];
