export const metadataLabelMappings = {
  approval_date: { label: "Approval FY" },
  organisation: { label: "Fund" },
  theme: { label: "Theme" },
  geographies: { label: "Geography" },
  sector: { label: "Sector" },
  implementing_agency: { label: "Implementing Agencies" },
  project_value_fund_spend: { label: "Fund Spend" },
  project_value_co_financing: { label: "Co-financing" },
  result_area: { label: "Results areas" },
  status: { label: "Status" },
  project_url: { label: "Source" },
  focal_area: { label: "Focal Area" },
  category: { label: "Category" },
  document_type: { label: "Type" },
};
