export const RESULTS_PER_PAGE = 20;
const RESULTS_PER_CONTINUATION_TOKEN = 100;
export const PAGES_PER_CONTINUATION_TOKEN = RESULTS_PER_CONTINUATION_TOKEN / RESULTS_PER_PAGE;

export const MAX_RESULTS = 500;
export const MAX_PAGES = MAX_RESULTS / RESULTS_PER_PAGE;

export const PASSAGES_PER_DOC = 50;
export const MAX_PASSAGES = 500;
