const SYSTEM_NO_GEOGRAPHY_CODE = "xaa";
export const SYSTEM_INTERNATIONAL_CODE = "xab";
export const SYSTEM_GEO_CODES = [SYSTEM_NO_GEOGRAPHY_CODE, SYSTEM_INTERNATIONAL_CODE];

const SYSTEM_NO_GEOGRAPHY_NAME = "no-geography";
export const SYSTEM_INTERNATIONAL_NAME = "international";
export const SYSTEM_GEO_NAMES = [SYSTEM_NO_GEOGRAPHY_NAME, SYSTEM_INTERNATIONAL_NAME];
