# Autoformatter friendly markdownlint config (all formatting rules disabled)
default: true

MD013:
  # Number of characters
  line_length: 80

  # Number of characters for headings
  heading_line_length: 80

  # Number of characters for code blocks
  code_block_line_length: 80

  # Include code blocks
  headings: true

  # Don't include tables
  tables: false
  code_blocks: false

  # Strict length checking
  strict: false

  # Stern length checking
  stern: false
