name: CI/CD

on:
  push:
    tags: [v*]
    branches:
      - main
  pull_request:
    # By default, a workflow only runs when a pull_request event's activity type is opened,
    # synchronize, or reopened.
    types: [opened, synchronize, reopened, edited]
    branches:
      - main

permissions: read-all

jobs:
  check-auto-tagging-will-work:
    if: |
      github.event_name == 'pull_request' &&
      (! startsWith(github.ref, 'refs/tags') && ! startsWith(github.ref, 'refs/heads/main'))
    uses: climatepolicyradar/reusable-workflows/.github/workflows/check-auto-tagging-will-work.yml@v8

  code-quality:
    if: |
      ! cancelled() && always() &&
      (needs.check-auto-tagging-will-work.result == 'skipped' || needs.check-auto-tagging-will-work.result == 'success') &&
      ! startsWith(github.ref, 'refs/tags')
    needs:
      - check-auto-tagging-will-work
    permissions:
      # For trunk to post annotations
      checks: write
      # For repo checkout
      contents: read
    uses: climatepolicyradar/reusable-workflows/.github/workflows/node-precommit-validator.yml@v5
    with:
      node-version: 20.11.0
      package-manager: npm

  theme-factory:
    if: |
      ! cancelled() && always() && (needs.code-quality.result == 'success')
    needs:
      - code-quality
    strategy:
      fail-fast: false
      matrix:
        theme: [cpr, cclw]
    permissions:
      contents: write
    secrets: inherit
    uses: climatepolicyradar/reusable-workflows/.github/workflows/theme-factory.yml@v6
    with:
      repo-name: navigator-frontend
      theme: ${{ matrix.theme }}

  update-pulumi-config:
    if: |
      ! cancelled() && always() && (needs.theme-factory.result == 'success')
    needs:
      - check-auto-tagging-will-work
      - theme-factory
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: |
          echo "${{ needs.check-auto-tagging-will-work.outputs.new_tag }}"
          filename=infra/Pulumi.staging.yaml
          docker_tag=${{ needs.check-auto-tagging-will-work.outputs.new_tag }}
          docker_tag=${docker_tag#v}
          sed -i -e s/DOCKER_TAG/"${docker_tag}"/g ${filename}
          cat ${filename}
          if grep -wq "${docker_tag}" ${filename}; then
            echo "${docker_tag} found in file"
          else 
            echo "${docker_tag} not found in file"
            exit 1
          fi

  deploy:
    if: |
      ! cancelled() && always() && (needs.update-pulumi-config.result == 'success')
    needs:
      - update-pulumi-config
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - run: pip install -r requirements.txt

      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: org-name/stack-name # When using an individual account, only use stack-name.
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

  release:
    if: ${{ ! cancelled() && always() && needs.theme-factory.result == 'success' && needs.theme-factory.outputs.new_tag != 'Skip' }}
    needs: theme-factory
    permissions:
      contents: write
    uses: climatepolicyradar/reusable-workflows/.github/workflows/release.yml@v6
