# trunk-ignore-all(checkov)

name: Deploy on merge
on:
  workflow_call:
    inputs:
      environment:
        # workflow_call does not support options
        # this is OK though as the values are generated via code
        description: Environment
        type: string
        required: true
      theme:
        description: Theme
        type: string
        required: true
      docker-tag:
        description: Docker tag
        type: string
        required: true
  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        type: choice
        required: true
        options:
          - staging
          - production
      theme:
        description: Theme
        type: string
        required: true
      docker-tag:
        description: Docker tag
        type: string
        required: true
permissions: read-all
jobs:
  deploy-on-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy
        uses: actions/github-script@v7
        with:
          # This is currently from the user jamesgorrie
          # TODO: use tech@climatepolicyradar.org user for this
          github-token: ${{ secrets.NAVIGATOR_INFRA_GITHUB_PAT }}
          script: |
            // This is because we did not prefix CPR as it was theme no. 1
            const stack = "${{ inputs.theme }}" === "cpr" ? "frontend/${{ inputs.environment }}" : "frontend/${{ inputs.theme }}-${{ inputs.environment }}";
            const result = await github.rest.actions.createWorkflowDispatch({
                owner: "climatepolicyradar",
                repo: "navigator-infra",
                workflow_id: "deploy.yml",
                ref: "main",
                inputs: {
                    "docker-tag": `${{ inputs.docker-tag }}`,
                    stack: stack
                }
            })
            // TODO: extend logging and reporting
            console.log(result)
