name: Merge to main
on:
  push:
    branches:
      - main
      - push-to-ecrt

# trunk-ignore(checkov/CKV2_GHA_1)
permissions: write-all
jobs:
  # Trunk check
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version-file: .nvmrc
      - name: Generate tsconfig.json
        run: |
          cp tsconfig.base.json tsconfig.json
          sed -i "s/__THEME__/$THEME/g" tsconfig.json
      - run: npm install
      - uses: trunk-io/trunk-action@v1
        with:
          arguments: --ci

  # Unit tests
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version-file: .nvmrc
      - run: npm install
      - run: cp .env.example .env
      - name: Generate tsconfig.json
        run: |
          cp tsconfig.base.json tsconfig.json
          sed -i "s/__THEME__/$THEME/g" tsconfig.json
        env:
          THEME: cpr
      - name: Run vitest - core functionality
        run: npm run test
        # This is needed to pass the results on to the trunk-io/analytics-uploader
        continue-on-error: true
        env:
          THEME: cpr

      - name: Run vitest - new features
        run: npm run test
        # This is needed to pass the results on to the trunk-io/analytics-uploader
        continue-on-error: true
        env:
          THEME: cpr
          E2E_TEST_FEATURE_FLAGS: true

      - name: Upload vitest results to Trunk.io
        uses: trunk-io/analytics-uploader@v2
        with:
          junit-paths: "**/vitest.xml"
          token: ${{ secrets.TRUNK_TOKEN }}
          org-slug: ${{ secrets.TRUNK_ORG_SLUG }}

  # Release builds for each theme
  release:
    runs-on: ubuntu-latest
    needs: [code-quality]
    strategy:
      fail-fast: false
      matrix:
        theme: [cpr, cclw, mcf, ccc]
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version-file: .nvmrc

      # build
      - run: |
          export THEME=${{ matrix.theme }}
          make build

      # release
      # most of this is taken from
      # https://docs.github.com/en/actions/use-cases-and-examples/deploying/deploying-to-amazon-elastic-container-service#creating-the-workflow
      - name: Configure AWS credentials (staging)
        uses: aws-actions/configure-aws-credentials@v6.2.3
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID_STAGING }}:role/navigator-frontend-github-actions
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: eu-west-1
      - name: Login to Amazon ECR (staging)
        id: login-ecr-staging
        uses: aws-actions/amazon-ecr-login@03f1aad4c6c7ffd436567f42f9384779290529bd
      - name: Build, tag, and push image to Amazon ECR (staging)
        id: build-image-staging
        env:
          ECR_REGISTRY: ${{ secrets.DOCKER_REGISTRY_STAGING }}
          IMAGE_TAG: ${{ github.sha }}
          AWS_REGION: eu-west-1
          ECR_REPOSITORY: navigator-frontend-${{ matrix.theme }}
          THEME: ${{ matrix.theme }}
        run: |
          docker build --build-arg THEME=${THEME} --build-arg NEXT_PUBLIC_FARO_ENVIRONMENT=staging -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Configure aws credentials (production)
        uses: aws-actions/configure-aws-credentials@v6.2.3
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID_PROD }}:role/navigator-frontend-github-actions
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: eu-west-1
      - name: Login to Amazon ECR (production)
        id: login-ecr-prod
        uses: aws-actions/amazon-ecr-login@03f1aad4c6c7ffd436567f42f9384779290529bd

      - name: Build, tag, and push image to Amazon ECR (production)
        id: build-image-prod
        env:
          ECR_REGISTRY: ${{ secrets.DOCKER_REGISTRY_PROD }}
          IMAGE_TAG: ${{ github.sha }}
          AWS_REGION: eu-west-1
          ECR_REPOSITORY: navigator-frontend-${{ matrix.theme }}
          THEME: ${{ matrix.theme }}
        run: |
          docker build --build-arg THEME=${THEME} --build-arg NEXT_PUBLIC_FARO_ENVIRONMENT=production -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

  # Deploy Storybook
  storybook:
    runs-on: ubuntu-latest
    env:
      THEME: cpr
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version-file: .nvmrc
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.2.3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      - name: Generate tsconfig.json
        run: |
          cp tsconfig.base.json tsconfig.json
          sed -i "s/__THEME__/$THEME/g" tsconfig.json
      - run: npm install
      - run: npm run build-storybook
      - name: Upload to S3
        run: |
          aws s3 sync --delete ./storybook-static s3://storybook.climatepolicyradar.org
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-1
